---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
components:
  - ../../components/alerts
  - ../../components/common
resources:
  - ./cert-issuers/ks.yaml
  - ./trust-manager/ks.yaml
  - ./trust-bundles/ks.yaml
  - ./cert-manager/ks.yaml
