---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-garage-access-key
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "database/${APP}-garage-access-key"
    reloader.stakater.com/auto: "true"
