---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
components:
  - ../../components/alerts
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./1password/ks.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./kubernetes-dashboard/ks.yaml
  - ./features
  - ./secrets
  - ./spegel/ks.yaml
  - ./reflector/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./external-secrets
  - ./registry/ks.yaml
  - ./etcd-backup/ks.yaml
  # - ./multus/ks.yaml
  - ./github-token/ks.yaml
