---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}-primary
spec:
  name: AdGuard Home (Primary)
  category: Infrastructure
  url: &url https://${APP}-primary.${CLUSTER_DOMAIN}/index.html
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/adguard-home.svg
  access_policy:
    groups:
      - admins
  gatus:
    - group: "AdGuard Home"
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}-secondary
spec:
  name: AdGuard Home (Secondary)
  category: Infrastructure
  url: &url https://${APP}-secondary.${CLUSTER_DOMAIN}/index.html
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/adguard-home.svg
  access_policy:
    groups:
      - admins
  gatus:
    - group: "AdGuard Home"
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}-tertiary
spec:
  name: AdGuard Home (Tertiary)
  category: Infrastructure
  url: &url https://${APP}-tertiary.${CLUSTER_DOMAIN}/index.html
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/adguard-home.svg
  access_policy:
    groups:
      - admins
  gatus:
    - group: "AdGuard Home"
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
