---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./chrony/ks.yaml
  # - ./matter/ks.yaml
  - ./mosquitto/ks.yaml
  - ./home-assistant/ks.yaml
  - ./opencloud/ks.yaml
