---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: CloudBeaver
  category: ${CLUSTER_TITLE}
  description: CloudBeaver - web based database manager
  icon: https://dbeaver.com/wp-content/uploads/2022/06/favicon-32x32.png
  url: &url "https://sql.${CLUSTER_DOMAIN}"
  access_policy:
    groups:
      - admins
  authentik:
    proxy:
      mode: "forward_single"
      externalHost: *url
  #     skipPathRegex: "^/api([/?].*)?$"
  gatus:
    - url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
