---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        TIME_ZONE: "${TIMEZONE}"
        LANGUAGE_CODE: "en"
        SITE_NAME: "${CLUSTER_TITLE} Seafile"

        SEAFILE_SERVER_HOSTNAME: "${APP}.${ROOT_DOMAIN}"
        SEAFILE_SERVER_PROTOCOL: "https"
        INIT_SEAFILE_ADMIN_EMAIL: "{{ .admin_username }}"
        INIT_SEAFILE_ADMIN_PASSWORD: "{{ .admin_password }}"
        JWT_PRIVATE_KEY: "{{ .config_password }}"
        INIT_SEAFILE_MYSQL_ROOT_PASSWORD: "{{ .config_mysql_root_password }}"
        MARIADB_ROOT_PASSWORD: "{{ .config_mysql_root_password }}"
        SEAFILE_MYSQL_DB_USER: seafile
        SEAFILE_MYSQL_DB_PASSWORD: "{{ .config_mysql_root_password }}"
        SEAFILE_MYSQL_DB_HOST: "127.0.0.1"
        SEAFILE_MYSQL_DB_PORT: "3306"
        ENABLE_GO_FILESERVER: "True"
        CACHE_PROVIDER: redis
        REDIS_HOST: "valkey.database.svc.cluster.local"
        REDIS_PORT: "6379"
        LOGIN_URL: https://${APP}.${ROOT_DOMAIN}/oauth/login/
        # CSRF_TRUSTED_ORIGINS: "https://${APP}.${ROOT_DOMAIN}"
        CLIENT_SSO_VIA_LOCAL_BROWSER: "True"

        # ENABLE_REMOTE_USER_AUTHENTICATION: "True"
        # REMOTE_USER_HEADER: 'X-Authentik-Email'
        # REMOTE_USER_DOMAIN: '${ROOT_DOMAIN}'
        # REMOTE_USER_CREATE_UNKNOWN_USER: "True"
        # REMOTE_USER_ACTIVATE_USER_AFTER_CREATION: "True"
        # REMOTE_USER_ATTRIBUTE_MAP: |
        #   {
        #     'X-Authentik-Name': 'name',
        #     'X-Authentik-Email': 'contact_email',
        #     'X-Authentik-Groups': 'affiliation',
        #   }

        ENABLE_OAUTH: "True"
        OAUTH_CLIENT_ID: "{{ .oidc_client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        OAUTH_PROVIDER: "${CLUSTER_TITLE}"
        OAUTH_PROVIDER_DOMAIN: "${OIDC_ISSUER}"
        OAUTH_AUTHORIZATION_URL: "{{ .oidc_authorization_url }}"
        OAUTH_TOKEN_URL: "{{ .oidc_token_url }}"
        OAUTH_USER_INFO_URL: "{{ .oidc_userinfo_url }}"
        OAUTH_SCOPE: "openid email profile groups"
        OAUTH_REDIRECT_URL: "https://${APP}.${ROOT_DOMAIN}/oauth/callback/"
        OAUTH_CREATE_UNKNOWN_USER: "True"
        OAUTH_ACTIVATE_USER_AFTER_CREATION: "True"
        OAUTH_ATTRIBUTE_MAP: |
          {
            "id": (False, "email"),
            "email": (True, "email"),
            "name": (False, "name"),
            "sub": (False, "uid"),
          }
        OAUTH_ROLE_ATTRIBUTE: "groups"
        OAUTH_ADMIN_GROUP: "admins"
  dataFrom:
    - extract:
        key: 'Seafile Config'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "config_$1"
    - extract:
        key: 'Seafile Admin'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "admin_$1"

    - extract:
        key: '${CLUSTER_CNAME}-${APP}-oidc-credentials'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "oidc_$1"
