---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        TIME_ZONE: "${TIMEZONE}"
        LANGUAGE_CODE: "en"
        SITE_NAME: "${CLUSTER_TITLE} Seafile"
        JWT_PRIVATE_KEY: "{{ .config_password }}"

        SEAFILE_SERVER_HOSTNAME: "${APP}.${ROOT_DOMAIN}"
        SEAFILE_SERVER_PROTOCOL: "https"
        SEAFILE_LOG_TO_STDOUT: "True"

        ENABLE_ENCRYPTED_LIBRARY: "True"
        ENCRYPTED_LIBRARY_VERSION: "4"
        ENABLE_WATERMARK: "True"
        ENABLE_REPO_HISTORY_SETTING: "True"
        ENABLE_SHARE_TO_ALL_GROUPS: "True"
        ENABLE_USER_CLEAN_TRASH: "True"
        SHARE_LINK_LOGIN_REQUIRED: "True"

        # ENABLE_SEADOC: "True"
        # SEAHUB_SERVICE_URL: http://seafile

        # ENABLE_NOTIFICATION_SERVER: "True"
        # NOTIFICATION_SERVER_LOG_LEVEL: "info"

        # MD_PORT: "8084"
        # MD_STORAGE_TYPE: disk
        # MD_LOG_LEVEL: info
        # MD_MAX_CACHE_SIZE: "1GB"
        # MD_CHECK_UPDATE_INTERVAL: "30m"
        # MD_FILE_COUNT_LIMIT: "100000"

        # ENABLE_VIDEO_THUMBNAIL: "True"
        SEAF_SERVER_STORAGE_TYPE: disk

        INIT_SEAFILE_ADMIN_EMAIL: "{{ .admin_username }}"
        INIT_SEAFILE_ADMIN_PASSWORD: "{{ .admin_password }}"
        INIT_SEAFILE_MYSQL_ROOT_PASSWORD: "{{ .config_mysql_root_password }}"

        SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: seafile_db
        SEAFILE_MYSQL_DB_CCNET_DB_NAME: ccnet_db
        SEAFILE_MYSQL_DB_SEAHUB_DB_NAME: seahub_db
        SEAFILE_MYSQL_DB_USER: seafile
        SEAFILE_MYSQL_DB_PASSWORD: "{{ .config_mysql_root_password }}"
        SEAFILE_MYSQL_DB_HOST: "127.0.0.1"
        SEAFILE_MYSQL_DB_PORT: "3306"

        ENABLE_GO_FILESERVER: "True"
        CACHE_PROVIDER: redis
        REDIS_HOST: "valkey.database.svc.cluster.local"
        REDIS_PORT: "6379"
        CSRF_TRUSTED_ORIGINS: "https://${APP}.${ROOT_DOMAIN}"
        CLIENT_SSO_VIA_LOCAL_BROWSER: "True"
        # ENABLE_ADFS_LOGIN: "True"
        # DISABLE_ADFS_USER_PWD_LOGIN: "True"

        ENABLE_OAUTH: "True"
        OAUTH_CLIENT_ID: "{{ .oidc_client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        OAUTH_PROVIDER: "authentik"
        OAUTH_PROVIDER_DOMAIN: "authentik"
        OAUTH_AUTHORIZATION_URL: "{{ .oidc_authorization_url }}"
        OAUTH_TOKEN_URL: "{{ .oidc_token_url }}"
        OAUTH_USER_INFO_URL: "{{ .oidc_userinfo_url }}"
        OAUTH_SCOPE: "openid email profile groups"
        OAUTH_REDIRECT_URL: "https://${APP}.${ROOT_DOMAIN}/oauth/callback/"
        OAUTH_CREATE_UNKNOWN_USER: "True"
        OAUTH_ACTIVATE_USER_AFTER_CREATION: "True"
        OAUTH_ATTRIBUTE_MAP: |
          {
            "id": (False, "email"),
            "email": (True, "email"),
            "name": (False, "name"),
            "sub": (False, "uid"),
          }
        OAUTH_ROLE_ATTRIBUTE: "groups"
        OAUTH_ADMIN_GROUP: "admins"
  dataFrom:
    - extract:
        key: 'Seafile Config'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "config_$1"
    - extract:
        key: 'Seafile Admin'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "admin_$1"

    - extract:
        key: '${CLUSTER_CNAME}-${APP}-oidc-credentials'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "oidc_$1"
