---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app seafile
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  interval: 1h
  timeout: 10m
  install:
    createNamespace: true
    replace: true
    remediation:
      retries: 7
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 7
      strategy: rollback
  rollback:
    force: false
    cleanupOnFail: true
    recreate: true
  uninstall:
    keepHistory: false
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        initContainers:
          set-ownership:
            image:
              repository: busybox
              tag: latest@sha256:b3255e7dfbcd10cb367af0d409747d511aeb66dfac98cf30e97e87e4207dd76f
            command: ['sh', '-c', 'chown -R root:root /shared']
        containers:
          seafile:
            image:
              repository: seafileltd/seafile-mc
              tag: 13.0-latest@sha256:d9a472513b826eb9c807caa52faccabc8b65a97ccbc806d98968aaea8dc0d79f
            envFrom:
              - secretRef:
                  name: ${APP}-env
            dependsOn:
              - zmariadb
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 2Gi
          zmariadb:
            image:
              repository: mariadb
              tag: lts@sha256:7fcb6109db2ba31b22a5709c1eaf9e84f76c9f1b9b9031ef09f24092f7f207cc
            env:
              MARIADB_USER: seafile
              MARIADB_PASSWORD:
                secretKeyRef:
                  name: ${APP}-env
                  key: INIT_SEAFILE_MYSQL_ROOT_PASSWORD
              MARIADB_ROOT_PASSWORD:
                secretKeyRef:
                  name: ${APP}-env
                  key: INIT_SEAFILE_MYSQL_ROOT_PASSWORD
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
      seadoc:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        containers:
          seadoc:
            image:
              repository: seafileltd/sdoc-server
              tag: 2.0-latest
            envFrom:
              - secretRef:
                  name: ${APP}-env
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
      # notification-server:
      #   annotations:
      #     reloader.stakater.com/auto: "true"
      #   replicas: 1
      #   containers:
      #     notification-server:
      #       image:
      #         repository: seafileltd/notification-server
      #         tag: 13.0-latest
      #       envFrom:
      #         - secretRef:
      #             name: ${APP}-env
      #       resources:
      #         requests:
      #           cpu: 50m
      #           memory: 256Mi
      #         limits:
      #           memory: 1Gi
      # md-server:
      #   annotations:
      #     reloader.stakater.com/auto: "true"
      #   replicas: 1
      #   containers:
      #     md-server:
      #       image:
      #         repository: seafileltd/seafile-md-server
      #         tag: 13.0-latest
      #       envFrom:
      #         - secretRef:
      #             name: ${APP}-env
      #       resources:
      #         requests:
      #           cpu: 50m
      #           memory: 256Mi
      #         limits:
      #           memory: 1Gi
      thumbnail-server:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        containers:
          thumbnail-server:
            image:
              repository: seafileltd/thumbnail-server
              tag: 13.0-latest
            envFrom:
              - secretRef:
                  name: ${APP}-env
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi

    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          *app :
            set-ownership:
              - path: /shared
                subPath: seafile
              - path: /mysql
                subPath: mysql
            seafile:
              - path: /shared
                subPath: seafile
            mariadb:
              - path: /var/lib/mysql
                subPath: mysql
          seadoc:
            seadoc:
              - path: /shared
                subPath: seafile
          notification-server:
            notification-server:
              - path: /shared
                subPath: seafile
          thumbnail-server:
            thumbnail-server:
              - path: /shared
                subPath: seafile
          md-server:
            md-server:
              - path: /shared
                subPath: seafile
      tmp:
        type: emptyDir
        advancedMounts:
          *app :
            seafile:
              - path: /shared/seafile/logs
                subPath: seafile
          seadoc:
            seadoc:
              - path: /shared/seafile/logs
                subPath: seadoc
          notification-server:
            notification-server:
              - path: /shared/seafile/logs
                subPath: notification-server
          thumbnail-server:
            thumbnail-server:
              - path: /shared/seafile/logs
                subPath: thumbnail-server
          md-server:
            md-server:
              - path: /shared/seafile/logs
                subPath: md-server


    service:
      *app :
        controller: *app
        type: ClusterIP
        ports:
          http:
            port: &port 80
      mariadb:
        controller: *app
        type: ClusterIP
        ports:
          http:
            port: &mariadb-port 3306
      seadoc:
        controller: seadoc
        type: ClusterIP
        ports:
          http:
            port: &seadoc-port 80
      # notification-server:
      #   controller: notification-server
      #   type: ClusterIP
      #   ports:
      #     http:
      #       port: &notification-server 80
      thumbnail-server:
        controller: thumbnail-server
        type: ClusterIP
        ports:
          http:
            port: &thumbnail-server-port 80
      # md-server:
      #   controller: md-server
      #   type: ClusterIP
      #   ports:
      #     http:
      #       port: &md-server-port 80

    route:
      internal:
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "${APP}.${ROOT_DOMAIN}"
          - "files.${ROOT_DOMAIN}"
        kind: HTTPRoute
        rules:
          - backendRefs:
              - identifier: *app
                port: *port
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: local-user
      seadoc:
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "seadoc.${ROOT_DOMAIN}"
          - "docs.${ROOT_DOMAIN}"
        kind: HTTPRoute
        rules:
          - backendRefs:
              - identifier: seadoc
                port: *seadoc-port
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: local-user
