---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name tdarr-node
  namespace: &namespace sgc
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
      driscoll.dev/name: *name
  dependsOn: []
  path: ./kubernetes/apps/sgc/media/tdarr-node
  prune: true
  wait: true
  force: false
  interval: 1h
  timeout: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components: []
  postBuild:
    substitute:
      APP: *name
      NAMESPACE: *namespace
