---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/ingress.json
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APP}-receive-ingress-tailscale
  annotations:
    tailscale.com/proxy-group: ingress
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
    tailscale.com/tags: "tag:observability"
spec:
  ingressClassName: tailscale
  rules:
    - host: "${APP}-receive-ingress.${TAILSCALE_DOMAIN}"
      http:
        paths:
          - path: /api/v1/receive
            pathType: Prefix
            backend:
              service:
                name: thanos-receive
                port:
                  name: remote
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thanos-receive
                port:
                  name: http
  tls:
    - hosts:
        - ${APP}-receive-ingress
