---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alertmanager-secret.yaml
  - ./helmrelease.yaml
  - ./scrapeconfig.yaml
  - ./definition.yaml
  - ./ingress.yaml
configMapGenerator:
  - name: alertmanager-config-tpl
    files:
      - alertmanager.yaml=./resources/alertmanager.yaml
generatorOptions:
  disableNameSuffixHash: true
