
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &app apc-ups-1
spec:
  staticConfigs:
    - targets:
        - "${ALPHA_SITE_IP}:3493"
      labels:
        ups:  *app
  metricsPath: /ups_metrics
  params:
    ups: [ *app ]
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &app apc-ups-2
spec:
  staticConfigs:
    - targets:
        - "${ALPHA_SITE_IP}:3493"
      labels:
        ups:  *app
  metricsPath: /ups_metrics
  params:
    ups: [ *app ]
