---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "kube-prometheus-stack-receive-ingress.${TAILSCALE_DOMAIN}"
    tailscale.com/proxy-group: egress
  name: kube-prometheus-stack-receive-ingress
spec:
  externalName: unused
  type: ExternalName
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "kube-prometheus-stack-receive-service.${TAILSCALE_DOMAIN}"
    tailscale.com/proxy-group: egress
  name: kube-prometheus-stack-receive-service
spec:
  externalName: unused
  type: ExternalName
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "thanos-receive-ingress.${TAILSCALE_DOMAIN}"
    tailscale.com/proxy-group: egress
  name: thanos-receive-ingress
spec:
  externalName: unused
  type: ExternalName
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "thanos-receive-service.${TAILSCALE_DOMAIN}"
    tailscale.com/proxy-group: egress
  name: thanos-receive-service
spec:
  externalName: unused
  type: ExternalName
