---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "thanos-write.${TAILSCALE_DOMAIN}"
    # tailscale.com/proxy-group: egress
  name: thanos-write-remote
spec:
  externalName: placeholder
  type: ExternalName
  ports:
    - name: grpc
      port: 10901
      protocol: TCP
