---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "thanos-remote-write.${TAILSCALE_DOMAIN}"
    tailscale.com/proxy-group: observability
  name: thanos-remote-write
spec:
  externalName: thanos-remote-write.${TAILSCALE_DOMAIN}
  type: ExternalName
  ports:
    - port: 19291
      targetPort: 19291
      name: remote-write
