---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./cronjob.yaml
  - ./secret.yaml
configMapGenerator:
  - name: github-token-scripts
    files:
      - refresh-token.sh=./resources/refresh-token.sh
generatorOptions:
  disableNameSuffixHash: true
