---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: loki-http
  namespace: observability
spec:
  interval: 5m
  module: http_404
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://loki-headless.observability.svc.cluster.local:3100
