---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
    name: crowdsec-secret
    annotations:
      reloader.stakater.com/auto: "true"
spec:
    itemPath: vaults/Eris/items/Crowdsec ApiKey
