---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: traefik-internal
spec:
  name: Traefik Dashboard
  category: ${CLUSTER_TITLE}
  description: Access to the Traefik dashboard
  url: &url https://internal.${CLUSTER_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/traefik.svg
  access_policy:
    groups:
      - admins
  authentik:
    proxy:
      mode: "forward_single"
      externalHost: *url
  gatus:
    - url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
