---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-releases depName=kubernetes-sigs/gateway-api
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/experimental-install.yaml
  - ./tls-settings.yaml
  - ./crowdsec-secret.yaml
  - ./helmrelease.yaml
  - ./definition.yaml
  - ./middleware
  - ./external-gateway.yaml
  - ./error-pages.yaml
configMapGenerator:
  - name: traefik-internal-values
    files:
      - values.yaml=./values.yaml
    options:
      disableNameSuffixHash: true
