---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: egress
spec:
  type: egress
  hostnamePrefix: ${CLUSTER_CNAME}-egress
  replicas: 2
  tags: ["tag:egress"]
  proxyClass: default
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: management
spec:
  type: egress
  hostnamePrefix: ${CLUSTER_CNAME}-management
  replicas: 2
  tags: ["tag:management"]
  proxyClass: default
