---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: &name "${CLUSTER_CNAME}-router"
spec:
  hostname: *name
  subnetRouter:
    advertiseRoutes:
      - "${CLUSTER_NETWORK}"
      - "${SERVICE_NETWORK}"
  tags:
    - "tag:${CLUSTER_CNAME}"
