apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - values.yaml=./values.yaml
  name: traefik-internal-values
  options:
    disableNameSuffixHash: true
kind: Kustomization
namespace: network
resources:
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/experimental-install.yaml
- ./helmrelease.yaml
- ./definition.yaml
- ./middleware
- ./external.yaml
- ./error-pages.yaml
