---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
    name: media-management-credentials
    annotations:
      reloader.stakater.com/auto: "true"
spec:
    itemPath: vaults/Eris/items/Media Management Secrets
