---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "luna.${TAILSCALE_DOMAIN}"
    tailscale.com/proxy-group: ssh
  name: proxmox-luna
spec:
  externalName: luna
  type: ExternalName
  ports:
    - port: 8006
      targetPort: 8006
      name: pve
    - port: 8007
      targetPort: 8007
      name: pbs
    - port: 22
      targetPort: 22
      name: ssh
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "celestia.${TAILSCALE_DOMAIN}"
    tailscale.com/proxy-group: ssh
  name: proxmox-celestia
spec:
  externalName: celestia
  type: ExternalName
  ports:
    - port: 8006
      targetPort: 8006
      name: pve
    - port: 8007
      targetPort: 8007
      name: pbs

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "alpha-site.${TAILSCALE_DOMAIN}"
    tailscale.com/proxy-group: ssh
  name: proxmox-alpha-site
spec:
  externalName: alpha-site
  type: ExternalName
  ports:
    - port: 8006
      targetPort: 8006
      name: pve
    - port: 3493
      targetPort: 3493
      name: nut
    - port: 22
      targetPort: 22
      name: ssh
