---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-etcd-restic-keys
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: talos-etcd-restic-keys
    creationPolicy: Owner
  data:
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: Volsync Password
        property: credential
