---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Valkey Standalone
  category: ${CLUSTER_TITLE}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/valkey.svg
  gatus:
    - group: "Database"
      url: tcp://valkey-sa.database.svc.cluster.local:6379
      conditions:
      - "[CONNECTED] == true"
  access_policy:
    groups:
      - admins
