---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-operations
  namespace: &namespace pulumi
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: pulumi-secrets
      namespace: *namespace
  path: ./kubernetes/apps/pulumi/stacks/home
  prune: true
  wait: true
  force: false # true
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik
  namespace: &namespace pulumi
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: home-operations
      namespace: *namespace
  path: ./kubernetes/apps/pulumi/stacks/authentik
  prune: true
  wait: true
  force: false # true
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app applications
  namespace: &namespace pulumi
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: home-operations
      namespace: *namespace
    - name: authentik
      namespace: *namespace
  path: ./kubernetes/apps/pulumi/stacks/applications
  prune: true
  wait: true
  force: false # true
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
