---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-remote-cluster
  namespace: sgc
spec:
  targetNamespace: sgc
  commonMetadata:
    labels:
      app.kubernetes.io/name: authentik-remote-cluster
      driscoll.dev/name: authentik-remote-cluster
  dependsOn: []
  path: ./kubernetes/apps/sgc/idp/authentik-remote-cluster
  prune: true
  wait: false
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
