---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authentik-remote-cluster-config
type: Opaque
stringData:
  sa: "authentik-remote-cluster"
  cluster: "${CLUSTER_CNAME}"
  cluster_api: "apiserver.${CLUSTER_DOMAIN}"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-outpost-push-secret
spec:
  deletionPolicy: None
  refreshInterval: 24h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword-connect
  selector:
    secret:
      name: authentik-remote-cluster
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: &key ${CLUSTER_CNAME}-authentik-outpost
          property: token
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
    - match:
        secretKey: ca.crt
        remoteRef:
          remoteKey: *key
          property: certificate
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-outpost-push-secret-config
spec:
  deletionPolicy: None
  refreshInterval: 24h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword-connect
  selector:
    secret:
      name: authentik-remote-cluster-config
  data:
    - match:
        secretKey: sa
        remoteRef:
          remoteKey: &key ${CLUSTER_CNAME}-authentik-outpost
          property: sa
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
    - match:
        secretKey: cluster
        remoteRef:
          remoteKey: *key
          property: cluster
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
    - match:
        secretKey: cluster_api
        remoteRef:
          remoteKey: *key
          property: cluster_api
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
