---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./connector.yaml
  - ./dns-config.yaml
  - ./externalsecret.yaml
  - ./ingress.yaml
  - ./egress.yaml
  - ./proxy.yaml
  # - ./recorder.yaml
