---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: thanos-query-observability
spec:
  name: Thanos Query
  category: &category Observability
  description: Thanos is a highly available, long term Prometheus setup with global query view.
  url: &url https://thanos.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/thanos.svg
  access_policy:
    groups:
      - admins
  authentik:
    proxy:
      mode: "forward_single"
      externalHost: *url
  gatus:
    - group: *category
      url: https://thanos.${ROOT_DOMAIN}
      method: GET
      conditions:
        - "[STATUS] == 200"
# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
# apiVersion: driscoll.dev/v1
# kind: ApplicationDefinition
# metadata:
#   name: loki-observability
# spec:
#   name: Loki
#   category: Observability
#   description: Loki is a log aggregation system designed to work with Prometheus.
#   url: &url https://loki.${ROOT_DOMAIN}
#   icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/loki.svg
#   access_policy:
#     groups:
#       - admins
#   authentik:
#     proxy:
#       mode: "forward_single"
#       externalHost: *url
#   gatus:
#     - group: "System"
#       url: https://loki.${ROOT_DOMAIN}/ready
#       method: GET
#       conditions:
#         - "[STATUS] == 200"
