---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./definition.yaml
  - ./ingress.yaml
configMapGenerator:
- name: thanos-ruler
  files:
  - ruler.yml=./resources/ruler.yml
  options:
    disableNameSuffixHash: true
