---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/ingress.json
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-tailscale-query-ingress
  annotations:
    tailscale.com/proxy-group: ingress
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
    tailscale.com/tags: "tag:observability"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: thanos-query-frontend
      port:
        name: http
