---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/ingress.json
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-query
  annotations:
    tailscale.com/proxy-group: ingress
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
    tailscale.com/tags: "tag:observability"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: thanos-query-frontend
      port:
        name: http
  tls:
    - hosts:
        - thanos
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/ingress.json
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-write
  annotations:
    tailscale.com/tags: "tag:observability"
    tailscale.com/proxy-group: ingress
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
spec:
  ingressClassName: tailscale
  rules:
    - host: thanos-write
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thanos-receive
                port:
                  name: http
          - path: /api/v1/receive
            pathType: Prefix
            backend:
              service:
                name: thanos-receive
                port:
                  name: grpc
  tls:
    - hosts:
        - thanos-write
