---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./definition.yaml
  - ./thanos-write.yaml
  - ./alertmanager-operated.yaml
  - ./externalsecret.yaml
generatorOptions:
  disableNameSuffixHash: true
