---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authenticated-user
spec:
  chain:
    middlewares:
      - name: ak-outpost-proxy
        namespace: ${CLUSTER_CNAME}
      - name: internal-network
