---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: "${SPIKE_IP}"
  share: /mnt/stash
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
mountOptions:
  - nfsvers=4.2
  - hard
  - intr
  - nconnect=16
  - noatime
  - rsize=1048576
  - wsize=1048576
reclaimPolicy: Retain
volumeBindingMode: Immediate
