---
# Kubelet directory path, if kubelet configured to use other than /var/lib/kubelet path.
kubeletDir: /var/lib/kubelet

serviceAccount:
  create: true

rbac:
  create: true
  name: csi-nfs

driver:
  name: nfs.csi.k8s.io
  mountPermissions: 0

feature:
  enableFSGroupPolicy: true
  enableInlineVolume: false
  propagateHostMountOptions: false

controller:
  name: csi-nfs-controller
  replicas: 2
  enableSnapshotter: false

externalSnapshotter:
  enabled: true
