---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: matter
  namespace: sgc
spec:
  targetNamespace: sgc
  commonMetadata:
    labels:
      app.kubernetes.io/name: matter
  path: ./kubernetes/apps/sgc/home/matter
  prune: true
  wait: true
  force: false
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  dependsOn:
    - name: volsync
      namespace: volsync-system
    - name: sgc-secrets
      namespace: sgc
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: matter
      NAMESPACE: sgc
      VOLSYNC_CAPACITY: 4Gi
