---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Grafana
  category: &category Observability
  description: Grafana is an open-source platform for monitoring and observability.
  url: &url https://${APP}.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/grafana.svg
  access_policy:
    groups:
      - friends
      - family
  authentik:
    oauth2:
      clientType: confidential
      allowedRedirectUris:
      - url: "https://${APP}.${ROOT_DOMAIN}/login/generic_oauth"
      propertyMappings:
        - email
        - openid
        - profile
      includeClaimsInIdToken: true
      subMode: user_email
  gatus:
    - group: *category
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
