---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tautulli
  namespace: sgc
spec:
  targetNamespace: sgc
  commonMetadata:
    labels:
      app.kubernetes.io/name: tautulli
      driscoll.dev/name: tautulli
  dependsOn:
    - name: plex
      namespace: sgc
    - name: volsync
      namespace: volsync-system
  path: ./kubernetes/apps/sgc/media/tautulli
  prune: true
  wait: true
  force: false
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tautulli
      namespace: sgc
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: tautulli
      NAMESPACE: sgc
      TAILSCALE_HOST: tautulli-sgc
