---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: OpenCloud
  category: Applications
  description: OpenCloud is a self-hosted cloud storage solution that offers file sharing, collaboration, and synchronization features, similar to services like Nextcloud or ownCloud.
  url: &url https://cloud.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/opencloud.svg
  access_policy:
    groups:
      - family
      - friends
  authentik:
    oauth2:
      clientType: confidential
      allowedRedirectUris:
        - url: https://cloud.${ROOT_DOMAIN}/
        - url: https://cloud.${ROOT_DOMAIN}/oidc-callback.html
        - url: https://cloud.${ROOT_DOMAIN}/oidc-silent-redirect.html
        - url: http://127.0.0.1
        - url: http://localhost
        - url: oc://android.opencloud.eu
        - url: oc://ios.opencloud.eu
        - url: x-cyberduck-action:oauth
        - url: x-mountainduck-action:oauth
      propertyMappings:
        - email
        - openid
        - profile
      includeClaimsInIdToken: true
      subMode: user_email
  gatus:
    - group: "Applications"
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
