---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./definition.yaml
configMapGenerator:
  - name: opencloud-values
    files:
      - values.yaml=./values.yaml
generatorOptions:
  disableNameSuffixHash: true
