---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./adguard/ks.yaml
  - ./cloudflare/ks.yaml
  - ./records/ks.yaml
  - ./unifi/ks.yaml
