---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/k8s.mariadb.com/mariadb_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: ${APP}
spec:
  rootPasswordSecretKeyRef:
    name: ${APP}-superuser
    key: password
    generate: false

  image: "mariadb:12.1.2@sha256:e1bcd6f85781f4a875abefb11c4166c1d79e4237c23de597bf0df81fec225b40"

  storage:
    size: 10Gi
    storageClassName: ${CLUSTER_STORAGE_BLOCK}
    resizeInUseVolumes: true
    waitForVolumeResize: true

  service:
    type: LoadBalancer

  podSecurityContext:
    runAsUser: 0
  securityContext:
    allowPrivilegeEscalation: false

  podDisruptionBudget:
    maxUnavailable: 33%

  updateStrategy:
    autoUpdateDataPlane: true
    type: RollingUpdate

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi

  metrics:
    enabled: true

  bootstrapFrom:
    s3:
      bucket: ${BACKBLAZE_DB_BUCKET}
      prefix: mariadb
      endpoint: s3.us-east-005.backblazeb2.com
      accessKeyIdSecretKeyRef:
        name: mariadb-secret
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: mariadb-secret
        key: secret-access-key
      tls:
        enabled: true
