---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/traefik.io/ingressroutetcp_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ${APP}-internal
  annotations:
    reloader.stakater.com/auto: "true"
    external-dns.alpha.kubernetes.io/target: "${INTERNAL_DOMAIN}"
    external-dns.alpha.kubernetes.io/hostname: ${APP}.${CLUSTER_DOMAIN}
    kubernetes.io/ingress.class: internal
spec:
  entryPoints:
  - mariadb
  routes:
  - match: HostSNI("*")
    services:
    - name: ${APP}
      port: 3306
