---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./definition.yaml
  - ./thanos-receive.yaml
  - ./alertmanager-operated.yaml
  - ./externalsecret.yaml
  - ./probes.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: prometheus-values
    files:
      - values.yaml=./values.yaml
generatorOptions:
  disableNameSuffixHash: true
