---
# Blackbox exporter probes for prometheus proxy services (thanos, alertmanager, loki)
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: thanos-receive-http
  namespace: observability
spec:
  interval: 5m
  module: http_2xx
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://thanos-receive.observability.svc.cluster.local:10901
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: alertmanager-http
  namespace: observability
spec:
  interval: 5m
  module: http_2xx
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://alertmanager-operated.observability.svc.cluster.local:9093
