---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./serviceaccount.yaml
  - ./equestria.yaml
  - ./sgc.yaml
  - ./celestia.yaml
  - ./luna.yaml
  - ./alpha-site.yaml
