apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-user.yaml
  - postgres-user.sops.yaml
  - postgres-superuser.yaml
  - postgres-superuser.sops.yaml
  - authentik.yaml
  - authentik.sops.yaml
  - crowdsec.yaml
  - crowdsec.sops.yaml