# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: zitadel-postgres-password
stringData:
  username: ENC[AES256_GCM,data:ps3mAxUTBw==,iv:U+XrKkbQqJw32YIClelWhlz08HS2+WuLweOO0tR9Y0A=,tag:wG9wxW4i/oPtGm6T1iV8HA==,type:str]
  database: ENC[AES256_GCM,data:SUYd3LTBiw==,iv:AIra7NyzcM1t3sNg8RKL69E08LeGeQj01/y7VtVfIUQ=,tag:uQXC0oMY3qRMosyA9EQ+dg==,type:str]
  port: ENC[AES256_GCM,data:9mcTqg==,iv:oUH4MGG7tXfNL5zRmdouJ6Qxw5iqi7VgzOROqwK1SgU=,tag:ReVjFFoQjBRGsSc7grpqiA==,type:str]
  hostname: ENC[AES256_GCM,data:25gfcyHu9i0PN+9Z2buYU5407J4zU+LXVBA0FRFpxD/gPw9yCJY=,iv:YDjrDGyU6qq7T2P8qt7jKL5gIdJajOk9ovrzoIS0Zpw=,tag:dJORUDWqc7/iTXHK9TfJsg==,type:str]
  password: ENC[AES256_GCM,data:kR277O9fVn/RFbQgguEp+01ifRxQMjlpzzrAGhKdwJ0=,iv:QGHNmaa89CR9bwLsWUexLrGRRc/kHcr275jcaBYTSXo=,tag:85GmvvrxvW1hjBXfIlTAfQ==,type:str]
sops:
  age:
    - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNHZBUDFhT1BpeXBURWd4
        QmxUdFFTbHBTRmJZclZFVWV4OVlqTXorYWo4CnlqdCsvZVZqOEtmWUVJM1RvSmNs
        ZGNjWkJEMGhVTjcrZ3ZSUHZCTW1iS3cKLS0tIDJSc01LdmZiZVdNL3ZsaFBTVCta
        aWh6WElhWWJ3RHdkSWowUEdkcVZFSkkKGgylRDYlef2cLpZiKmm8Pmpy+MR2ZuAM
        4QUVlsFgzVKxVwT9ftD5d1C1K2WsiLuGYtyNABG+xZT5paj11VqfzA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OHR0dURHSGJwZ0wyRmtI
        bmNhUUw0SEtqVFR1Qm01d1BqbU5rL3NFelU0CjFObWNDWHFPWU9lL3RtRjZyMVc2
        a3Zua2JsZVAvSjJFRTl0MUlCcG84L2sKLS0tIEFjRHZ1TWpLUkRpQWUzU3cvVEJX
        emI2Q1NUYUEvSmN0U21vdS8zbnZUQTQKqbMa3a59VlRkgUSQQJKzvyVkJsPeVeDx
        06KDXpTffNJAM8dz8sH8GgdPaKMM3N+j72Gt4gcuO7444FyzZsx5Bw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbW5HeFpHTDg4TmRlaDZH
        ZXlBRlN3dmVGelFQRCt3Vk8vVldvOW5KQmpJCnlDRmsrVkZTa2tVZDdqbEJKY0Yw
        bWplZTFzYk1Va1k2Q0dWbUgyWHFtTUUKLS0tIGR3T1JRQjlveEN1V051dGFvQVA1
        VUxuMURTQ2g3a0lKQ0IydnFzV0VoaDQKSB9R2EamrIFwPwcLbu4+2WTHKyO+4fXl
        FXaLrhRCO/i4+4uLBX+0mo3mm8WqSu+5fEbXxlbWs3rEkXClkAp4Dg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-10T03:34:52Z"
  mac: ENC[AES256_GCM,data:11weyLMG7WLaXgQ5lUFr5fuBks1svZjQOL7eOH2xtF6nQLo2FYQQ1iIM9mFFock7cIhvh3rVOY9uO2AK3Ep09mCjH969IG95YUC3sEq9C5V+8diuJqFvTtBPken8C2YOC3nbQd8y/RXZIBRunoRWOGMFylE4CoJ4RiNNCiB/aiU=,iv:4sD+TDLXzq9ZSUtIQbSqevBfruScDe36zgG+jYDNdJ4=,tag:U0MGrrsExC0aBNPCIfA96w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
