---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: oxycloud
spec:
  name: OxyCloud
  category: Applications
  description: Cloud management and monitoring platform.
  url: https://cloud.${ROOT_DOMAIN}
  icon: https://raw.githubusercontent.com/DioCrafts/OxiCloud/refs/heads/main/static/oxicloud-logo.svg
  access_policy:
    groups:
      - friends
      - family
  authentik:
    oauth2:
      clientType: confidential
      allowedRedirectUris:
      - url: "https://cloud.${ROOT_DOMAIN}/oidc/callback/authentik"
      propertyMappings:
        - email
        - openid
        - profile
      includeClaimsInIdToken: true
      subMode: user_email
  gatus:
    - url: https://home.${ROOT_DOMAIN}
      method: GET
      conditions:
        - "[STATUS] == 200"
