apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  CLUSTER_CNAME: ENC[AES256_GCM,data:pQ7H,iv:UWcb61Rk+crmY6o4+xz8+NgKl5tWl14a9g10tvw4Q4M=,tag:3rZUl5dW4VErIOmo4uhuVg==,type:str]
  CLUSTER_KEY: ENC[AES256_GCM,data:LoL+,iv:5uAOfqbXgOQ5+uQ2IWO1/PxOhOQw/pvI1w0bfUZwk1g=,tag:z7BMeqMewLZV/osJrrhpLA==,type:str]
  CLUSTER_TITLE: ENC[AES256_GCM,data:Jle4e3zbL5TgOYvhKDaKeQ==,iv:ymqZeNCID36RiOgDCGLWzfCF8bUwE2y9kigTdI4vweo=,tag:WdNIOnUnSFQYKjO4/My9nA==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:wH4XvGghgoxkgsyzoJ1f0FA=,iv:/xS1vkSFgfWDIPRNtE/qwmacOgTaQ/6w2wI6nIVwAos=,tag:0qj43jgJgu3ukRvVtEZ4hQ==,type:str]
  CLUSTER_IP: ENC[AES256_GCM,data:kLvC291NWjMmuNw=,iv:gIl6gsEucEuabV7hHmefJQ5p8gE2zWYkcYxbQBhb9qw=,tag:rPuyQ7voN9MWonXrnvXrdw==,type:str]
  CLUSTER_API_IP: ENC[AES256_GCM,data:DuqIftP0pwZNKjQ2lA==,iv:biCM09Vkfd3sa3SgQBmqHapNwZkTtDUWblhhN4ZyP5g=,tag:HpGreZFtNzFOar48n4qLeg==,type:str]
  ACME_EMAIL: ENC[AES256_GCM,data:YrIQTFsKPPsC+mKh7H4JdwaxZD14Euh9B5i02TgRlgIXc2w8Qq6huoyUZsZ8okdbiQ==,iv:i5e8rCBlxY+lFutU89Hbmw0q56EQ1jYoG5qfwqtyuP4=,tag:RMntUgtHXwDyXxdNqBK6GQ==,type:str]
  CLUSTER_TAILSCALE_DOMAIN: ENC[AES256_GCM,data:1NXErVmhaYcAiDSuUJpFzLjJUvMi,iv:WH0GlZhMtcNuABV3nCEyjp9DnS2eD7A01OA+7VTS+MY=,tag:bRGbRcMnJtHvuIQuKmb/Hg==,type:str]
  INTERNAL_CLUSTER_DOMAIN: ENC[AES256_GCM,data:PJpWSJf8Qs/wc4G78Q==,iv:8A8Wu6PBF3ruPBxdrzGFzVjqT9r/EPOY6J4mike2ABU=,tag:nzG6kI8QVvE9rCE2XDFgvw==,type:str]
  INTERNAL_CLUSTER_SERVICE: ENC[AES256_GCM,data:R8XU0U2gd3JX5Q4umn+q8AurtmOm,iv:J8+UhsvU2UBzTjApfEqpkxh3TsH1P1iimhbTVx6eKns=,tag:Eow1PBpxNrD4ZrYPp6pK1Q==,type:str]
  INTERNAL_CNAME: ENC[AES256_GCM,data:DnIN+em92Q==,iv:s2IQj94U2sg6fzVg82c2nKcHbRuKqXUKC4eirQ6GrEk=,tag:ZGTN5hHHVisWpVSp1AB/sw==,type:str]
  INTERNAL_DOMAIN: ENC[AES256_GCM,data:b1AG76vILps8oh8aPHnv+rE+o77c,iv:QBo9/wmGltpkW9wdA15ppfZucq9y2+0XGio1zmL16Js=,tag:0jAcEZN88kz3wlx6IlV6Nw==,type:str]
  INTERNAL_IP: ENC[AES256_GCM,data:z18eyv4WN/DjZe3N7A==,iv:tTTl1RazXvdyaga/ZydIWJCad7ukQ8YO4S0Goxq9lNo=,tag:gaGbfW8G92s6OiFVmWu3yA==,type:str]
  INTERNAL_TAILSCALE_VIP: ENC[AES256_GCM,data:pASpihxQyCVhaKgPLiXn,iv:ISjZ2SlTAuZbAnX3ucsSEN2+EiY7ILFAj9OjYW5g5fo=,tag:UqydQs8QeTpLG0DWLHwncg==,type:str]
  EXTERNAL_CNAME: ENC[AES256_GCM,data:+vQOj+PdXA==,iv:CWGqz+szbw4PdVXKUmRUEizuycQzEMkz2KKptfY/aSY=,tag:SMa1JmP46nK/w1S+IP6+vQ==,type:str]
  EXTERNAL_DOMAIN: ENC[AES256_GCM,data:wDHoYV8vhTUxLAp3RMc6MVPL9c7Y,iv:eL17pR10BdVsmuUhSyQT6gLxk5D9nGvFGJ9Ax3pHaAc=,tag:lIH80Jev5TwifFYtEtPLQw==,type:str]
  EXTERNAL_IP: ENC[AES256_GCM,data:L55JvAHbVcfmKomznA==,iv:XrqXLRCAMoML+Gg+nYH3FjnmKzov4ikE9hR7ENBmHlQ=,tag:da1z2GihmA64uGibTp33Wg==,type:str]
  EXTERNAL_TAILSCALE_VIP: ENC[AES256_GCM,data:t8KcVBom0YIh+/jHlUPS,iv:pX1wT34n2iGfqA6jAhHNuwfo3kpzb7JbFhrlmlIlyWY=,tag:atN5VYZYEbGyuPccjwQ6Rw==,type:str]
  K8S_GATEWAY_IP: ENC[AES256_GCM,data:5oV9JmPEeHZAMk5RaQ==,iv:FjzhKLMkYjgrkHoIpMiVZf/ycEMhwqCNhb43N/4kngk=,tag:KCgzJxB3rxl9/IOI/iZp8w==,type:str]
  TUNNEL_DOMAIN: ENC[AES256_GCM,data:NoxzFJhyGfFNwyx8mRKaockOf1pR3hS4wRWHF2IgidaeCT5TnocJYaDd495cESVv2wZWCLM=,iv:e2l5Ica9+2OJRdq1rwyEOs1fUJtD/WqvotYBjD5dHj4=,tag:OSD3vPjCZ1x3b9GiXjUXHQ==,type:str]
  CLOUDFLARE_TUNNEL_SECRET: ENC[AES256_GCM,data:YORx7c4lqVtzUPyJj+0hRPq/G/ZzvL2YTypwsL7S2LcR2rfQ1eG+C+JbcBE=,iv:gLt3q+baF8jUvxh+/T+6Dhdo6U/X4LpBx7PEA+2iECg=,tag:abfgLk7ib3SPr9UzJ2vASw==,type:str]
  CLUSTER_NETWORK: ENC[AES256_GCM,data:L+CnNYxzbPqKoIBnoA==,iv:/hKOyY0rDVb0QOsTyEnRyUBdXcfW1Iq+dUqZyeNFpa8=,tag:jGb7Ozx/Icz3HP4tB9oSWA==,type:str]
  SERVICE_NETWORK: ENC[AES256_GCM,data:o5HEAdvzexhGiJVfqQ==,iv:xukHNs2FiTOHwQ6DBRtMw7hGXK5vjiC/BZt+4LZCWGQ=,tag:ovC0fs2kkzCTB8cV3c8jaA==,type:str]
  ADGUARD_VIP: ENC[AES256_GCM,data:jw7WZawwaOp4ErMPTw==,iv:xN5+qakapQo3HNKEtdBnjUXkXdfAG2YlxfulLNkcStk=,tag:UCPsU1O9pp4h4g9V2jj3qQ==,type:str]
  ADGUARD_TAILSCALE_VIP: ENC[AES256_GCM,data:d3oBJ4isbrtrppr4wNJK,iv:2WJ15CCeQ7ru4ycB8RdrmEG/2H9MCGJUEVEOjIu7oi8=,tag:UVOGohW8l4WqqjPLPIvCeg==,type:str]
  CHRONY_VIP: ENC[AES256_GCM,data:LF/LRmg3OjRl+RHgqQ==,iv:lSgh0enQIxbvq4Nnt7o0BdLO+E13O7QO2S4dheota0E=,tag:mGKfx+9pqEVjTGd+P6n4PA==,type:str]
  CHRONY_TAILSCALE_VIP: ENC[AES256_GCM,data:4i0Op+gtE1UQbGUaWLsU,iv:YpEIoYkQumVCYUtvBF6W5D1h4Owj7bK+TdVHjBYPDx4=,tag:S+I3Rm0tGGdG0/bb1NnLCg==,type:str]
  AUTOMATION_VIP: ENC[AES256_GCM,data:faNY37TqHTHyb/bbmg==,iv:69s31O6goVBgZB+y32AIYFHlO7KbCYjm5WDuzeAUNyY=,tag:nDABlmf9ZoZW8DR64wcO8Q==,type:str]
  AUTOMATION_TAILSCALE_VIP: ENC[AES256_GCM,data:+zAwBLLaRE6EcaTs6EHq,iv:SgFJgQSHoZgV8Dio3gB02MqZWpjKj/6kdpkedIjidmY=,tag:qTQYejSi4ufdLWVNlNCzWA==,type:str]
  AUTOMATION_CNAME: ENC[AES256_GCM,data:EvmxhtrhjsT7Eg==,iv:Vv/4Mcx260EDcNje4h+yNefl5n/tyG/o6js4GF0s5Do=,tag:SNV3TRZmdtaFp6pr7wXYHw==,type:str]
  AUTOMATION_DOMAIN: ENC[AES256_GCM,data:qi9dyvxO1AsLRNxipSdtk8/jy7M+VcW7,iv:J13B3/r4Sfeb1JHRsJOi4QV5i4BuFoz5nnyaaxQCOpg=,tag:3/2h3F6HHuglwtgWdLn0Ig==,type:str]
  TUNER_VIP: ENC[AES256_GCM,data:2t3WPok911Xao4WZlQ==,iv:0Vi6KM8K8G1dFtgNJKl2izp+uiFBsAQXBkrHNEB2jEQ=,tag:sLdc40Pj4xiRcUd59M6uIA==,type:str]
  TUNER_TAILSCALE_VIP: ENC[AES256_GCM,data:tJpqrwFirf+sLOOq59eM,iv:OdvR7NGrhMP5aX/LdtZqQi7c403NbAapKtEq8HdwwFI=,tag:gH/nO7mns+oU0QxK+Qf5WQ==,type:str]
  TUNER_CNAME: ENC[AES256_GCM,data:mqBs3f0=,iv:UyWRSB3cVgUGFRDd302v51Gx98ygJHUyCRgZtMA0m+g=,tag:gZbOOtk/Z8VDuReuEIn5Hg==,type:str]
  TUNER_DOMAIN: ENC[AES256_GCM,data:uIyyg5hFqJce45lrI5TGL6XPvQ==,iv:J8cQpQoN0O8CBPI4ClrNQrPr3X0P60xDXrXp+7YKxXE=,tag:wxbfru+JVLx5+ExfsCWWmw==,type:str]
  SCRYPTED_VIP: ENC[AES256_GCM,data:bO4MHTku0Ma7SOOQGg==,iv:E/wJOhManXrwXCaWhl/5LA9aGT7w9TxS9G0AGtz5y0Y=,tag:wm+ZQJw+UfjkgzcUKj/R9w==,type:str]
  SCRYPTED_TAILSCALE_VIP: ENC[AES256_GCM,data:/qDV39N1x09qVunRTPUs,iv:vfFiWnjXX+Hfjfd/rx7UcozQlSyNlwTtClC5fGb5Q8Y=,tag:EO6zXjqTDkXguWpEfoeX0Q==,type:str]
  SCRYPTED_DOMAIN: ENC[AES256_GCM,data:UEITxHgFF0tqjaeFSe+jfd1G,iv:SkCIHStjf22iB1oD9um8FpZ+5Yi7st0daTxvwXiURaI=,tag:5QA5cazp+wqyrT1oqerAxA==,type:str]
  HOME_ASSISTANT_SSH_URL: ENC[AES256_GCM,data:9D1LT62zv6Y1SgGBDm5iN95TarcsX/TAdFm0nvb4gHkNZVJ9onAeLbDWd5DnQHKFGFPYFpcubQ==,iv:yS9dpvAPEj9L5sgOQrNFqjWsH/bZqULfTBOJnDAFLFg=,tag:r1EF0PP4GXLmKMSMpyI6YA==,type:str]
  TAILSCALE_NAMESERVER_IP: ENC[AES256_GCM,data:xo2xYQ1OHgsh7fPvmQ==,iv:4dIsRTANwuStu7Jh+WayK/FZqD2zLLyWwDosE1dMHhk=,tag:A8TjbRNiolhU26ARU3gwtg==,type:str]
  TAILSCALE_IDP_IP: ENC[AES256_GCM,data:Z7XkxzyDzTXRT0KZ2DK0,iv:xVI/LVNSFOZsYx8bQpXV0S0rz6fRnNs0fd6xxPjt1Q0=,tag:g89oo0xjtbIiCwfPgTi/hA==,type:str]
  OIDC_ISSUER: ENC[AES256_GCM,data:Q4uJoNQQTnmIGyQTuZIRaiYh,iv:sLYCISAJazsxolCKK7nb6BR2/lPh/kTZ+LKYUP2zJCc=,tag:nyMTS+W7JuhOqztE2AYOog==,type:str]
  S3_VOLUME_CAPACITY: ENC[AES256_GCM,data:lSE=,iv:RqWYvdlL49J1XaSCCHNEPY+tCGClCeRXGRCc8aBj4hU=,tag:m5WEmRYXU1FzugasYwcn7Q==,type:str]
  BACKBLAZE_S3: ENC[AES256_GCM,data:0tUJ7PzJdibS2VBy5bWKBv2hOrdGX1llQyFO98Y=,iv:Q/AkHy+7godym4TR6Z0fXnXUIQXCg9k/S1K332yRTt4=,tag:MWHc0lw9brnXFErXjBZt6g==,type:str]
  BACKBLAZE_DATABASE: ENC[AES256_GCM,data:iVE4Ad0Yuk0OQ22B+35pa+3C/7+IX49YHi4Y1SlBo6QIbC27GTw=,iv:Gio8v++khXfo24P9nGIr0TZHNvGvNVNAW6ms8CH7KfM=,tag:nsPaFNbOo53+ELIa1awdtg==,type:str]
  BACKBLAZE_DB_BUCKET: ENC[AES256_GCM,data:egg+w3jG1RtHRRWq4TY4gJuAtw==,iv:KOp/5RwiYNSpSsDgRi+KJFog/Rxql+zczxC362JKbv0=,tag:RrV47Kr1TEjanPf0wPAtcw==,type:str]
  BACKBLAZE_BUCKET: ENC[AES256_GCM,data:wmK1ssU0bsPzc8EHU/kyFQ==,iv:h1VEeG6a6zSsUJJvid3KZ7RO/YzS5d2P/GKIefPnFVU=,tag:K/j8dB3bqBOxnBz7Vl420A==,type:str]
  POSTGRES_REQUESTS_CPU: ENC[AES256_GCM,data:iSa64g==,iv:+8n+AJATLnJ/YZpD/0gnRRjDSF7Da4CE2W/UL9VmOT4=,tag:EFyqcVBJcLR9OngwlES8Lg==,type:str]
  POSTGRES_REQUESTS_MEMORY: ENC[AES256_GCM,data:6a0/,iv:mvOY42thH+93TL/Fk3OrNV71WbC9tkMIkf9WZdVwRHI=,tag:dj0scT2snwCMgUxpfTbx6g==,type:str]
  POSTGRES_LIMITS_CPU: ENC[AES256_GCM,data:YS5LfB8=,iv:BKXbFUNa4XtBgQu4xb+DHPxj/9b0LvIigrJ0HKrIhd8=,tag:YnGa7wE4qWRo8JZE2yrYmg==,type:str]
  POSTGRES_LIMITS_MEMORY: ENC[AES256_GCM,data:RAB7,iv:3SL51YeYsO/YfVaxWExeYdnMnd4aLIWROPGqn/ihmI4=,tag:EKec6ESsNf7lzV0i84GH/w==,type:str]
  POSTGRES_SHARED_BUFFERS: ENC[AES256_GCM,data:Y/pwpjw=,iv:7OOynRvQUwfEUNK3AJ5Oam3sACHGBGU05bCiBpBfQcI=,tag:8v6Ee2zSjrk9LeTmwlQ+xA==,type:str]
  TAILSCALE_CLIENT_SECRET: ENC[AES256_GCM,data:mPt/fNC6YVeIlQyKHvSJiwAUJA+BPmDHW1FzFbP7H3t8xihK/5x3Ew==,iv:PS96BY3z9IorU2FcNCfvJV5pZIgODJOQ9ESTBjBGbxA=,tag:7VcuEJzI/xZuVwginenU+A==,type:str]
sops:
  age:
    - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMm5wRzNwN3UzMHZGaUxm
        eFh3UnpvdzFERWxkSDFvYTdpeHN1clM5d2g0CkhuTjlCY2hWK0V0NGo1TDFzVDY2
        QkNDaEpWZkFPcXFZaThHY3NwRGJnMVUKLS0tIEJGajJSVHVyc09Xc1k4bFM2UmF5
        SVcyY0gzMmtnL1NKYWtiL2xidndvVmsK3Q6a+ZOoI44ON8K/MXwOGh7jR/c/SE2q
        a67axdaSb7QmlIAO7fGTneE2dkEBmcpJtblWP4j6ypeeqMZqcoOnWA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb00xMWpCQWZJL3k3OHJG
        L2haNmlvSjNUTGpISnBGOTRtZXZPNnd2ekN3CitiUHZZS1c1ZXdBN2MrMkVra1Zz
        Z09PRHY4RUVhU2RRY2U0U1hLZUJBR1kKLS0tIE1ZUlE5dnFyZlAxaFRnME1KcHJv
        Qkk0Qk5RcVJFcXMvbThrUzNCc1V4V0UKygCpJPpW7u65ZT/RowRdlrq5Rii36bVs
        U9dAwePQM1N5gGaziQxCz40RSaGAGotfEHCankONpKHUcA3dVk8oAg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoazR6dTY2VVhDMTFreFdV
        dlJKWDRXTVhKMUlheFVNbkhhYnE4Yzhna2dJClJmbTVFUkg3MTNScWpqQXF4b2Jj
        SmkyL3MybUQ5TUoxcWhkVVd2eC9YV2cKLS0tIDhDWDVOcXc1cXl3MnFSd2hkVHlJ
        WTRjOW9YNXgwRWxwSUhONUU1dS9CY1kK6MO9HFw6v/7aHQrVnRsiyofjvF9FZ8x3
        6IKY4hxXwzN57dUNI4uQizz2L2Yn2tPiFLosKXYJGKtw2d4WkzKEkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-12T01:38:32Z"
  mac: ENC[AES256_GCM,data:Jbduvmf9g9gj6ahC+uV9TGOK0fiHLacPItDcNsGHigUQ3qYsmaGztVx2TsDwaQIsrUg4jxcEosOZibKmOvB8wqSlK0krrDDhXxb/dy6UEUL5Rmpm6F8hkpewnnGeUbJibkpVX9EfdFCvDfGnhFmQKPIGp+3XXpAbXjlEiNwSR78=,iv:bmiVIbPNMm9zNyqvzbQLeGR08Pu0QUBXHE9zS52cpP0=,tag:xJIf5tnx2+RP1VhXAYM0qA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
