---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tailscale-redirect
spec:
  chain:
    middlewares: []
  # redirectRegex:
  #   regex: ^https?://(.*?)/(.*)
  #   replacement: https://${1}.${TAILSCALE_DOMAIN}/${2}
  #   permanent: true
