---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./definition.yaml
configMapGenerator:
- name: ${APP}-config
  files:
  - data-sources.json=./resources/data-sources.json
  - cloudbeaver.conf=./resources/cloudbeaver.conf
  options:
    disableNameSuffixHash: true
