---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: definition-crds-push-secret
spec:
  updatePolicy: IfNotExists
  deletionPolicy: None
  refreshInterval: 24h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword-connect
  selector:
    secret:
      name: definition-crds
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: &key ${CLUSTER_CNAME}-definition-crds
          property: token
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
    - match:
        secretKey: ca.crt
        remoteRef:
          remoteKey: *key
          property: certificate
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: definition-crds-push-secret-config
spec:
  updatePolicy: IfNotExists
  deletionPolicy: None
  refreshInterval: 24h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword-connect
  selector:
    secret:
      name: definition-crds-config
  data:
    - match:
        secretKey: sa
        remoteRef:
          remoteKey: &key ${CLUSTER_CNAME}-definition-crds
          property: sa
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
    - match:
        secretKey: cluster
        remoteRef:
          remoteKey: *key
          property: cluster
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
    - match:
        secretKey: cluster_api
        remoteRef:
          remoteKey: *key
          property: cluster_api
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
