---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-ip: "10.10.206.201"
    tailscale.com/proxy-group: management
  name: k8s-equestria
spec:
  externalName: k8s-equestria
  type: ExternalName
  ports:
    - port: 6443
      targetPort: 6443
      name: k8s
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-ip: "10.10.206.201"
    tailscale.com/proxy-group: management
  name: k8s-sgc
spec:
  externalName: k8s-sgc
  type: ExternalName
  ports:
    - port: 6443
      targetPort: 6443
      name: k8s
