---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pulumi
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./secret-store.yaml
  - ./shared/ks.yaml
  - ./stacks/ks.yaml
  - ./pulumi-operator/ks.yaml
