---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./golink.yaml
  - ./tsidp.yaml
  - ./secret.yaml
configMapGenerator:
  - files:
      - tsidp.sh=./resources/tsidp.sh
    name: tailscale-commands
generatorOptions:
  disableNameSuffixHash: true
