---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: egress
spec:
  type: egress
  hostnamePrefix: ${CLUSTER_CNAME}-egress
  replicas: 3
  tags: ["tag:egress"]
  proxyClass: proxy
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ssh
spec:
  type: egress
  hostnamePrefix: ${CLUSTER_CNAME}-ssh
  replicas: 2
  tags: ["tag:ssh"]
  proxyClass: proxy
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: observability
spec:
  type: egress
  hostnamePrefix: ${CLUSTER_CNAME}-observability
  replicas: 2
  tags: ["tag:observability"]
  proxyClass: proxy
