---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: egress
spec:
  type: egress
  hostnamePrefix: ${CLUSTER_CNAME}-egress
  replicas: 2
  tags: ["tag:egress"]
  proxyClass: accept-routes
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ssh
spec:
  type: egress
  hostnamePrefix: ${CLUSTER_CNAME}-ssh
  replicas: 2
  tags: ["tag:ssh"]
  proxyClass: accept-routes
