---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: kubeproxy
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  type: kube-apiserver
  replicas: 2
  tags: ["tag:${CLUSTER_CNAME}"]
  kubeAPIServer:
    mode: auth
