---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: kubeproxy
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  type: kube-apiserver
  kubeAPIServer:
    mode: auth
  replicas: 1
  tags:
    - "tag:k8s"
