---
# yaml-language-server: $schema=https://raw.githubusercontent.com/controlplaneio-fluxcd/charts/refs/heads/main/charts/flux-instance/values.schema.json
instance:
  distribution:
    # renovate: datasource=github-releases depName=controlplaneio-fluxcd/distribution
    version: 2.7.5
    registry: "ghcr.io/fluxcd"
  cluster:
    networkPolicy: false
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    name: flux-system
    kind: GitRepository
    url: "https://github.com/david-driscoll/stargate-command-cluster.git"
    ref: "refs/heads/main"
    path: kubernetes/flux/cluster
