# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser-password
stringData:
    password: ENC[AES256_GCM,data:2SlmK5MYOuPkKj5q0FA7ET0//7VukFAMqXt71KoIFc4=,iv:SLlpOpT1R7K7qQpx+CuRzCOlfp+AzZBJzHmhi60sHyk=,tag:WmTpcoed1G1/0qPAm0pEfQ==,type:str]
    username: ENC[AES256_GCM,data:dIObvhBlJ6g=,iv:aSteVG3dGNLVdN+yqhBSon3WGGCHVPGf36ADFDRAouc=,tag:UI4NJvH/j5PhJFmx0yN/lQ==,type:str]
    database: ENC[AES256_GCM,data:obOVPyB+jjc=,iv:NagfaSHGf35c16zPKpzDCcQOiY5gerC9bcDeRa7Cn/8=,tag:EzD6yL4UsTJ+/Jvh7DHJpQ==,type:str]
    port: ENC[AES256_GCM,data:wV10CQ==,iv:ln8VSvEadSNi0/G+EMjOr6LbJ6PorbRIF5nrZIrWZww=,tag:Z3LjlYPr2dos3ADne7ROiA==,type:str]
    hostname: ENC[AES256_GCM,data:6X5ltml+9GjXev7YOvwD8mBRclAzFNbJtpFdo9HAagPwrsWjiwc=,iv:hzBudPZ62OVVRHQShzYqmyNeIotctWE8XHEY58zBuWU=,tag:TzYX+Hh2dSJKI6/IVmNmEw==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK2xKZVRrUndmb3FPVTVx
            S3B3SEtVSW5jT0hNREJ0dnZsWVlONXZ1blI4CjdQUGtXK2lCeFVhcFRmejNmV2JN
            OW54OXJFN0EwdU8xZFlzNFBhSUhjbHcKLS0tIFJTUlpmcTdEM3ZXWDMzQytacTVU
            MDVLRHVUL2UzR3VCaUdxdjJaSmc5MzgKZooIWbhjzLw3H8o9ICgZjJRhTpkWiL0z
            lYJqJHSbjeMASdMFd+lKpZAXFBMf5fF0hydPAasa54J+ZUipifUlJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUlFqU25sdE9uN1VtbnRJ
            bG1lV3VtM245Vlp6QjBORUY4MmgwUjJWN2g0CjNmR1hvcStWRHM3S0JzM1RFeTZp
            L0FQVWc5TkFVNE5DZWZNL2FlcHdWRVUKLS0tIGQ0NkRLRUtCQ2dRZHl0MUtOV0tE
            bThTK2pKejZqclR3VW9QdUFMWnA3N1UKkY5SJ9YzWzK6hTx4crT50Jglg+70Zqrw
            aiMbc5Xw17GRdgW3+ywxu25YlJ4xsQTATgVz60+NEeH1+HmdQSLfwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaGxBenRPcDZIOXhON2hM
            RUZDc05SQk1XbktKSkFRZUJFNUpHYzBhb2dVClA5amN1NEdxM0N0bVVFY0t4Y3hw
            SDRKTFoycnBzMGxpdDFrM2taUSttT3MKLS0tIE9xQm9RSEVlZ2JFZ0VTYlg4M2dy
            WW9QRDdDTnpzN0NrSGhWZEptL2RhY0EKkVpGDDaqld75Q2/A8niz/TcBmKV2TwvM
            U9YGbz15YoyjgQkZG7snz/Hi0UOr9ZMxVz2IEAx5H1qIxuTKKUc6yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T18:20:10Z"
    mac: ENC[AES256_GCM,data:Afh75Hu1yy/fYebjz3eJRh3sjRHdQ1cBuuwRXYfhvCEth6CGWWOWk12HMnCLqpDIl+7d3iMM0PGkhBvZPWGge9T44bgvd+96iq4AfMorlRuMv/Z0G74hUIXu048vYXnNAkPbFFLZwnJAl2VDaR9vzE3hzi6zxagy+zWerIyKmK0=,iv:DXrJgHhE0vAUlMytwCCSAbPAi8wxmeSfGai+bSkOjXg=,tag:AaKEC12nhCypgHsijAOAzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: postgres-user-password
stringData:
    password: ENC[AES256_GCM,data:iSNj4NAApNSMMOmmE8ZzcBtf9LsOFn+k//T8y6htIG5DpwAWmDxvQVsndRp0SI1EsLtG9xwzcjiE48wrXMqMow==,iv:nmBuNzAR09aFem9snLgidXINgR4XZIgSmIit9WtIROg=,tag:zPY68VYvwegdHnIDXHNTSA==,type:str]
    username: ENC[AES256_GCM,data:seFywp/49sT3k/iZvc6CaQ==,iv:TaTRsMCcMkDwnLC+cnkrabP26eLJviN6/1hJs77yaVM=,tag:bqJaRjxRNy26lcbnOOqMbA==,type:str]
    database: ENC[AES256_GCM,data:2ENX30DsX3s=,iv:l0Zs6XdkVvAkk3iq53KUK/fAqN+pu6xM56CgBtW6ICU=,tag:LyMTZtJBGtSCUc9GzEZ0Sw==,type:str]
    port: ENC[AES256_GCM,data:wV10CQ==,iv:ln8VSvEadSNi0/G+EMjOr6LbJ6PorbRIF5nrZIrWZww=,tag:Z3LjlYPr2dos3ADne7ROiA==,type:str]
    hostname: ENC[AES256_GCM,data:6X5ltml+9GjXev7YOvwD8mBRclAzFNbJtpFdo9HAagPwrsWjiwc=,iv:hzBudPZ62OVVRHQShzYqmyNeIotctWE8XHEY58zBuWU=,tag:TzYX+Hh2dSJKI6/IVmNmEw==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK2xKZVRrUndmb3FPVTVx
            S3B3SEtVSW5jT0hNREJ0dnZsWVlONXZ1blI4CjdQUGtXK2lCeFVhcFRmejNmV2JN
            OW54OXJFN0EwdU8xZFlzNFBhSUhjbHcKLS0tIFJTUlpmcTdEM3ZXWDMzQytacTVU
            MDVLRHVUL2UzR3VCaUdxdjJaSmc5MzgKZooIWbhjzLw3H8o9ICgZjJRhTpkWiL0z
            lYJqJHSbjeMASdMFd+lKpZAXFBMf5fF0hydPAasa54J+ZUipifUlJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUlFqU25sdE9uN1VtbnRJ
            bG1lV3VtM245Vlp6QjBORUY4MmgwUjJWN2g0CjNmR1hvcStWRHM3S0JzM1RFeTZp
            L0FQVWc5TkFVNE5DZWZNL2FlcHdWRVUKLS0tIGQ0NkRLRUtCQ2dRZHl0MUtOV0tE
            bThTK2pKejZqclR3VW9QdUFMWnA3N1UKkY5SJ9YzWzK6hTx4crT50Jglg+70Zqrw
            aiMbc5Xw17GRdgW3+ywxu25YlJ4xsQTATgVz60+NEeH1+HmdQSLfwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaGxBenRPcDZIOXhON2hM
            RUZDc05SQk1XbktKSkFRZUJFNUpHYzBhb2dVClA5amN1NEdxM0N0bVVFY0t4Y3hw
            SDRKTFoycnBzMGxpdDFrM2taUSttT3MKLS0tIE9xQm9RSEVlZ2JFZ0VTYlg4M2dy
            WW9QRDdDTnpzN0NrSGhWZEptL2RhY0EKkVpGDDaqld75Q2/A8niz/TcBmKV2TwvM
            U9YGbz15YoyjgQkZG7snz/Hi0UOr9ZMxVz2IEAx5H1qIxuTKKUc6yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T18:20:10Z"
    mac: ENC[AES256_GCM,data:Afh75Hu1yy/fYebjz3eJRh3sjRHdQ1cBuuwRXYfhvCEth6CGWWOWk12HMnCLqpDIl+7d3iMM0PGkhBvZPWGge9T44bgvd+96iq4AfMorlRuMv/Z0G74hUIXu048vYXnNAkPbFFLZwnJAl2VDaR9vzE3hzi6zxagy+zWerIyKmK0=,iv:DXrJgHhE0vAUlMytwCCSAbPAi8wxmeSfGai+bSkOjXg=,tag:AaKEC12nhCypgHsijAOAzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgres-password
stringData:
    username: ENC[AES256_GCM,data:rLr61Dw6UmVf,iv:CzPp/PZsiLJaj0eC0yK00oyveZ4sqCH4TCFRQCDZN8k=,tag:mjtgRFWKT2kNcMANtmFTzA==,type:str]
    database: ENC[AES256_GCM,data:0PH0xwM6983X,iv:BkuAndk7asEsTXSCSE1XL6fjMRmEn0v3JhDGJU3YvX4=,tag:9k/maEWGwrYkxBKufjgLxw==,type:str]
    port: ENC[AES256_GCM,data:wV10CQ==,iv:ln8VSvEadSNi0/G+EMjOr6LbJ6PorbRIF5nrZIrWZww=,tag:Z3LjlYPr2dos3ADne7ROiA==,type:str]
    hostname: ENC[AES256_GCM,data:6X5ltml+9GjXev7YOvwD8mBRclAzFNbJtpFdo9HAagPwrsWjiwc=,iv:hzBudPZ62OVVRHQShzYqmyNeIotctWE8XHEY58zBuWU=,tag:TzYX+Hh2dSJKI6/IVmNmEw==,type:str]
    password: ENC[AES256_GCM,data:5AaC8Oy6OwqlbOJriP7HrCqIdtDlONYZWYSeBodx7+4=,iv:kEvTKf72U07ByQVgDXVKYiDCpoXNOzosZKoG5fHJGeE=,tag:iU67Yqnjpb0fd+HqeNUOAQ==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK2xKZVRrUndmb3FPVTVx
            S3B3SEtVSW5jT0hNREJ0dnZsWVlONXZ1blI4CjdQUGtXK2lCeFVhcFRmejNmV2JN
            OW54OXJFN0EwdU8xZFlzNFBhSUhjbHcKLS0tIFJTUlpmcTdEM3ZXWDMzQytacTVU
            MDVLRHVUL2UzR3VCaUdxdjJaSmc5MzgKZooIWbhjzLw3H8o9ICgZjJRhTpkWiL0z
            lYJqJHSbjeMASdMFd+lKpZAXFBMf5fF0hydPAasa54J+ZUipifUlJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUlFqU25sdE9uN1VtbnRJ
            bG1lV3VtM245Vlp6QjBORUY4MmgwUjJWN2g0CjNmR1hvcStWRHM3S0JzM1RFeTZp
            L0FQVWc5TkFVNE5DZWZNL2FlcHdWRVUKLS0tIGQ0NkRLRUtCQ2dRZHl0MUtOV0tE
            bThTK2pKejZqclR3VW9QdUFMWnA3N1UKkY5SJ9YzWzK6hTx4crT50Jglg+70Zqrw
            aiMbc5Xw17GRdgW3+ywxu25YlJ4xsQTATgVz60+NEeH1+HmdQSLfwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaGxBenRPcDZIOXhON2hM
            RUZDc05SQk1XbktKSkFRZUJFNUpHYzBhb2dVClA5amN1NEdxM0N0bVVFY0t4Y3hw
            SDRKTFoycnBzMGxpdDFrM2taUSttT3MKLS0tIE9xQm9RSEVlZ2JFZ0VTYlg4M2dy
            WW9QRDdDTnpzN0NrSGhWZEptL2RhY0EKkVpGDDaqld75Q2/A8niz/TcBmKV2TwvM
            U9YGbz15YoyjgQkZG7snz/Hi0UOr9ZMxVz2IEAx5H1qIxuTKKUc6yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T18:20:10Z"
    mac: ENC[AES256_GCM,data:Afh75Hu1yy/fYebjz3eJRh3sjRHdQ1cBuuwRXYfhvCEth6CGWWOWk12HMnCLqpDIl+7d3iMM0PGkhBvZPWGge9T44bgvd+96iq4AfMorlRuMv/Z0G74hUIXu048vYXnNAkPbFFLZwnJAl2VDaR9vzE3hzi6zxagy+zWerIyKmK0=,iv:DXrJgHhE0vAUlMytwCCSAbPAi8wxmeSfGai+bSkOjXg=,tag:AaKEC12nhCypgHsijAOAzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-postgres-password
stringData:
    username: ENC[AES256_GCM,data:ESJjoIHnZgM=,iv:RWcqXQ8lGMpASfMz/DJGsj5zGrKWfRCg7EHw9/dbEp4=,tag:nRbUIyE3VA2yL1aHn+RiPA==,type:str]
    database: ENC[AES256_GCM,data:awBfj/k/Dfw=,iv:s0sGb9ND0kQSq1twryXC0YM1sHwxJ5gJjm17pkGqnT0=,tag:ff0JtQlney7oCiKBHDSt0Q==,type:str]
    port: ENC[AES256_GCM,data:wV10CQ==,iv:ln8VSvEadSNi0/G+EMjOr6LbJ6PorbRIF5nrZIrWZww=,tag:Z3LjlYPr2dos3ADne7ROiA==,type:str]
    hostname: ENC[AES256_GCM,data:6X5ltml+9GjXev7YOvwD8mBRclAzFNbJtpFdo9HAagPwrsWjiwc=,iv:hzBudPZ62OVVRHQShzYqmyNeIotctWE8XHEY58zBuWU=,tag:TzYX+Hh2dSJKI6/IVmNmEw==,type:str]
    password: ENC[AES256_GCM,data:1gaeiTyWnQccw2mtCDb6Dt5QAlwsV2ujxb4v/VGiSGc=,iv:WIyqQP5pn1Lmx/aPXL6mvdPYbH5j0jusA8PhGZST4ps=,tag:PZ9F7xDBeXXhcc6d9vY17w==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK2xKZVRrUndmb3FPVTVx
            S3B3SEtVSW5jT0hNREJ0dnZsWVlONXZ1blI4CjdQUGtXK2lCeFVhcFRmejNmV2JN
            OW54OXJFN0EwdU8xZFlzNFBhSUhjbHcKLS0tIFJTUlpmcTdEM3ZXWDMzQytacTVU
            MDVLRHVUL2UzR3VCaUdxdjJaSmc5MzgKZooIWbhjzLw3H8o9ICgZjJRhTpkWiL0z
            lYJqJHSbjeMASdMFd+lKpZAXFBMf5fF0hydPAasa54J+ZUipifUlJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUlFqU25sdE9uN1VtbnRJ
            bG1lV3VtM245Vlp6QjBORUY4MmgwUjJWN2g0CjNmR1hvcStWRHM3S0JzM1RFeTZp
            L0FQVWc5TkFVNE5DZWZNL2FlcHdWRVUKLS0tIGQ0NkRLRUtCQ2dRZHl0MUtOV0tE
            bThTK2pKejZqclR3VW9QdUFMWnA3N1UKkY5SJ9YzWzK6hTx4crT50Jglg+70Zqrw
            aiMbc5Xw17GRdgW3+ywxu25YlJ4xsQTATgVz60+NEeH1+HmdQSLfwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaGxBenRPcDZIOXhON2hM
            RUZDc05SQk1XbktKSkFRZUJFNUpHYzBhb2dVClA5amN1NEdxM0N0bVVFY0t4Y3hw
            SDRKTFoycnBzMGxpdDFrM2taUSttT3MKLS0tIE9xQm9RSEVlZ2JFZ0VTYlg4M2dy
            WW9QRDdDTnpzN0NrSGhWZEptL2RhY0EKkVpGDDaqld75Q2/A8niz/TcBmKV2TwvM
            U9YGbz15YoyjgQkZG7snz/Hi0UOr9ZMxVz2IEAx5H1qIxuTKKUc6yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T18:20:10Z"
    mac: ENC[AES256_GCM,data:Afh75Hu1yy/fYebjz3eJRh3sjRHdQ1cBuuwRXYfhvCEth6CGWWOWk12HMnCLqpDIl+7d3iMM0PGkhBvZPWGge9T44bgvd+96iq4AfMorlRuMv/Z0G74hUIXu048vYXnNAkPbFFLZwnJAl2VDaR9vzE3hzi6zxagy+zWerIyKmK0=,iv:DXrJgHhE0vAUlMytwCCSAbPAi8wxmeSfGai+bSkOjXg=,tag:AaKEC12nhCypgHsijAOAzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-postgres-password
stringData:
    username: ENC[AES256_GCM,data:+aQDtRnE1g==,iv:Pd/5NSczyK9EbnbzT0CjTpKndIwkzs7roG0r84FdUjA=,tag:8mX4GA9V5hsn2y4dkzq7qQ==,type:str]
    database: ENC[AES256_GCM,data:q45yY1gqGQ==,iv:XIsl/DVJK/a21yK6PEYejOpjYxZuqO+9xmZt3VfXpGU=,tag:Yf9xmTKnvdrVh2zLPACdvw==,type:str]
    port: ENC[AES256_GCM,data:wV10CQ==,iv:ln8VSvEadSNi0/G+EMjOr6LbJ6PorbRIF5nrZIrWZww=,tag:Z3LjlYPr2dos3ADne7ROiA==,type:str]
    hostname: ENC[AES256_GCM,data:6X5ltml+9GjXev7YOvwD8mBRclAzFNbJtpFdo9HAagPwrsWjiwc=,iv:hzBudPZ62OVVRHQShzYqmyNeIotctWE8XHEY58zBuWU=,tag:TzYX+Hh2dSJKI6/IVmNmEw==,type:str]
    password: ENC[AES256_GCM,data:uMIFfqiD/TZurGNJs0Wryz7tezf6M8KTSRI5K6WEkNY=,iv:JVA/TFGgMTMrOdh/1LUw94PLIR2YlbYxetXfaDIeFlQ=,tag:oNEATCEfJIqhC4SdWn7e+w==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK2xKZVRrUndmb3FPVTVx
            S3B3SEtVSW5jT0hNREJ0dnZsWVlONXZ1blI4CjdQUGtXK2lCeFVhcFRmejNmV2JN
            OW54OXJFN0EwdU8xZFlzNFBhSUhjbHcKLS0tIFJTUlpmcTdEM3ZXWDMzQytacTVU
            MDVLRHVUL2UzR3VCaUdxdjJaSmc5MzgKZooIWbhjzLw3H8o9ICgZjJRhTpkWiL0z
            lYJqJHSbjeMASdMFd+lKpZAXFBMf5fF0hydPAasa54J+ZUipifUlJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUlFqU25sdE9uN1VtbnRJ
            bG1lV3VtM245Vlp6QjBORUY4MmgwUjJWN2g0CjNmR1hvcStWRHM3S0JzM1RFeTZp
            L0FQVWc5TkFVNE5DZWZNL2FlcHdWRVUKLS0tIGQ0NkRLRUtCQ2dRZHl0MUtOV0tE
            bThTK2pKejZqclR3VW9QdUFMWnA3N1UKkY5SJ9YzWzK6hTx4crT50Jglg+70Zqrw
            aiMbc5Xw17GRdgW3+ywxu25YlJ4xsQTATgVz60+NEeH1+HmdQSLfwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaGxBenRPcDZIOXhON2hM
            RUZDc05SQk1XbktKSkFRZUJFNUpHYzBhb2dVClA5amN1NEdxM0N0bVVFY0t4Y3hw
            SDRKTFoycnBzMGxpdDFrM2taUSttT3MKLS0tIE9xQm9RSEVlZ2JFZ0VTYlg4M2dy
            WW9QRDdDTnpzN0NrSGhWZEptL2RhY0EKkVpGDDaqld75Q2/A8niz/TcBmKV2TwvM
            U9YGbz15YoyjgQkZG7snz/Hi0UOr9ZMxVz2IEAx5H1qIxuTKKUc6yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T18:20:10Z"
    mac: ENC[AES256_GCM,data:Afh75Hu1yy/fYebjz3eJRh3sjRHdQ1cBuuwRXYfhvCEth6CGWWOWk12HMnCLqpDIl+7d3iMM0PGkhBvZPWGge9T44bgvd+96iq4AfMorlRuMv/Z0G74hUIXu048vYXnNAkPbFFLZwnJAl2VDaR9vzE3hzi6zxagy+zWerIyKmK0=,iv:DXrJgHhE0vAUlMytwCCSAbPAi8wxmeSfGai+bSkOjXg=,tag:AaKEC12nhCypgHsijAOAzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
