# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser-password
stringData:
    password: ENC[AES256_GCM,data:lsb2mS3au2TxVVc8TTKoJppk2mjxVlTfdBn/dvkG3Fo=,iv:gqL6BGo9K8oyBGXzT+49LeS8dZwy9GX23g3BmwAteII=,tag:KUB9t7SxX+MtVrLVVclNjw==,type:str]
    username: ENC[AES256_GCM,data:HK6dsav0zEc=,iv:SC414amPnGcA5z7h7T0DJ2zwIFt6Rse5QP2SCtod11k=,tag:CQiqWplWpnvVIJarxvfvGA==,type:str]
    database: ENC[AES256_GCM,data:/vKOXAYt1rw=,iv:53lH1HK8JOMvFXWJXohUO5RbsW0OmT27iBslSc+NgHY=,tag:q0TDUK7rEeKSTjBLpfLyYQ==,type:str]
    port: ENC[AES256_GCM,data:43tsNQ==,iv:Rs4kN0gJBYEZ9RPDvtFnb23TMRGTNb07VHGvN5IQfEg=,tag:oVBdNLZtNOVjM2Z2Y/rOjQ==,type:str]
    hostname: ENC[AES256_GCM,data:oKEbX3j6A6goC2kGyYjssX4GtAS4D/RR7c8ymaaOCUYVrHGYsPc=,iv:HvyX9P+oPgFty+xFTUxtXOx8cpVzrmmCTc8lxsMGKCo=,tag:9eE3TzPHKuucLklaReXydw==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueklKeFNKOWhwQ3d2dDN3
            ZU9uSnRORTJtS2lIbnVqTHU2c3hla0J4QkNRCkQvbW8rMXd3cStBS0grZWU0ZGdI
            MklTL0RNWCsybXhnOTZXaXlMM0dITnMKLS0tIGg0Sno3RWVseXhZWmo1T29oUElZ
            ZThrL2NYaGwxaVhFcVpOQllHV3Q5SzgK/MDwRyTeUSFA/wZSu9tW9pRxFCV9RxFS
            JjyxQC3ed15ncWE6t/7Iag6qJw6JpflhSS2VZhju5tbgQvWybHmNLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYzJNdlhtb21Zemsya2s1
            LzgvbjNFektxOU5xS2w2WWtPOFdnQjhDMERrCktYUXVTWFphWGpKS2RLcGIyMVlp
            TVVBdUVkVXcyRTQ1NnhQRXVjYVlWWUUKLS0tIGMvZTg1WHd6dmZTNTBISlR5SFZH
            QjAvdlMyQWdQQUozSUJ3MGhoUU9tQ0UK4hK6RYa5YiHL48d0X6Iiz6lk1gb2lD3y
            oLvsKyB4PoUDgkc1QG1l5eNVYqzSNMUJSJKJjA3aUKWL85iQ3+mgNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VWZEM1dRMEpOYklqYlM4
            bDl5dVJUaGhwYXIvWnpuK2F0RkpsNXc3WjE4CjZETFlhQWQyc25SVTY2alorbkc3
            LzRnRzRnSEVTSENHak5ESWI5aDVjS0EKLS0tIGtDcXRRUHhyU3BlSVhWQkF6c0FM
            YmE0bno4bExXc2ZyYVpRc05qQndrTFUKRzqPuTLrxc0enxdo9HG4KQz5X2OB1A1d
            Gw02Jlph1zp19X56iFuob4GAxCcJLR0cWjWwiLNmaMoX2zDCXZDgNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T18:38:17Z"
    mac: ENC[AES256_GCM,data:22rJGQv5AuxBTDzfOpjr0/BILRyGvZ9AwMITF/P2OPuMKZMtBjKltXKvrcyJ9i2dTz4WnXOql6ow/hBY1+5v9lkZNlM9QfE8RPYYtuJ1SAm9TwC3qbHmi6kxPa4bQ6F1e8rBrOibqOa8G3oUwEcHMLT/KWOwzIfXiLUNIvIvH1M=,iv:iJOmXeIn11z8HOZIoQoF1cLq3XXGJWqzimjUoE1eUDQ=,tag:z4NvqWFGhy6PtZvt4UfPQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: postgres-user-password
stringData:
    password: ENC[AES256_GCM,data:/1ha9Nzx1gXbYkKaTnnPWA6w50n9SBhKfymyV6FYG/5lGDxu4+ymoPrloY33KOoqfOu0B2aevIK0sqefbAI8Jg==,iv:iMRhg5M5hIW+T8PCcmsQrVc0Gk7VCStSA55e83m5Aqc=,tag:3zNPBUGjLoK8n2X2GKt5kQ==,type:str]
    username: ENC[AES256_GCM,data:+Ppy+uG2jbpFFKZ84iInUg==,iv:Ah8R0tKMIZnHL7UYV4thRqu9xbIzLTHxYvA1xHZO1Z0=,tag:dJjYC3jeKXrjSdRv6n48Dw==,type:str]
    database: ENC[AES256_GCM,data:/vKOXAYt1rw=,iv:53lH1HK8JOMvFXWJXohUO5RbsW0OmT27iBslSc+NgHY=,tag:q0TDUK7rEeKSTjBLpfLyYQ==,type:str]
    port: ENC[AES256_GCM,data:43tsNQ==,iv:Rs4kN0gJBYEZ9RPDvtFnb23TMRGTNb07VHGvN5IQfEg=,tag:oVBdNLZtNOVjM2Z2Y/rOjQ==,type:str]
    hostname: ENC[AES256_GCM,data:oKEbX3j6A6goC2kGyYjssX4GtAS4D/RR7c8ymaaOCUYVrHGYsPc=,iv:HvyX9P+oPgFty+xFTUxtXOx8cpVzrmmCTc8lxsMGKCo=,tag:9eE3TzPHKuucLklaReXydw==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueklKeFNKOWhwQ3d2dDN3
            ZU9uSnRORTJtS2lIbnVqTHU2c3hla0J4QkNRCkQvbW8rMXd3cStBS0grZWU0ZGdI
            MklTL0RNWCsybXhnOTZXaXlMM0dITnMKLS0tIGg0Sno3RWVseXhZWmo1T29oUElZ
            ZThrL2NYaGwxaVhFcVpOQllHV3Q5SzgK/MDwRyTeUSFA/wZSu9tW9pRxFCV9RxFS
            JjyxQC3ed15ncWE6t/7Iag6qJw6JpflhSS2VZhju5tbgQvWybHmNLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYzJNdlhtb21Zemsya2s1
            LzgvbjNFektxOU5xS2w2WWtPOFdnQjhDMERrCktYUXVTWFphWGpKS2RLcGIyMVlp
            TVVBdUVkVXcyRTQ1NnhQRXVjYVlWWUUKLS0tIGMvZTg1WHd6dmZTNTBISlR5SFZH
            QjAvdlMyQWdQQUozSUJ3MGhoUU9tQ0UK4hK6RYa5YiHL48d0X6Iiz6lk1gb2lD3y
            oLvsKyB4PoUDgkc1QG1l5eNVYqzSNMUJSJKJjA3aUKWL85iQ3+mgNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VWZEM1dRMEpOYklqYlM4
            bDl5dVJUaGhwYXIvWnpuK2F0RkpsNXc3WjE4CjZETFlhQWQyc25SVTY2alorbkc3
            LzRnRzRnSEVTSENHak5ESWI5aDVjS0EKLS0tIGtDcXRRUHhyU3BlSVhWQkF6c0FM
            YmE0bno4bExXc2ZyYVpRc05qQndrTFUKRzqPuTLrxc0enxdo9HG4KQz5X2OB1A1d
            Gw02Jlph1zp19X56iFuob4GAxCcJLR0cWjWwiLNmaMoX2zDCXZDgNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T18:38:17Z"
    mac: ENC[AES256_GCM,data:22rJGQv5AuxBTDzfOpjr0/BILRyGvZ9AwMITF/P2OPuMKZMtBjKltXKvrcyJ9i2dTz4WnXOql6ow/hBY1+5v9lkZNlM9QfE8RPYYtuJ1SAm9TwC3qbHmi6kxPa4bQ6F1e8rBrOibqOa8G3oUwEcHMLT/KWOwzIfXiLUNIvIvH1M=,iv:iJOmXeIn11z8HOZIoQoF1cLq3XXGJWqzimjUoE1eUDQ=,tag:z4NvqWFGhy6PtZvt4UfPQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-postgres-password
stringData:
    username: ENC[AES256_GCM,data:DdlQ1vQ3adA=,iv:Gle0vLW0JGlERVAQzZDsvmBgQ/gAKGo0ZsInmvdFcKQ=,tag:H/mtiwAKtn/Up4sC32q+6w==,type:str]
    database: ENC[AES256_GCM,data:1XlkaKoqQP4=,iv:4L5Y6bIm538d+M4l30eykz9d0M0ig0uKYDqeJzbJ/5A=,tag:e+H5zoLG/5TWFGdgtsP1Pw==,type:str]
    port: ENC[AES256_GCM,data:43tsNQ==,iv:Rs4kN0gJBYEZ9RPDvtFnb23TMRGTNb07VHGvN5IQfEg=,tag:oVBdNLZtNOVjM2Z2Y/rOjQ==,type:str]
    hostname: ENC[AES256_GCM,data:oKEbX3j6A6goC2kGyYjssX4GtAS4D/RR7c8ymaaOCUYVrHGYsPc=,iv:HvyX9P+oPgFty+xFTUxtXOx8cpVzrmmCTc8lxsMGKCo=,tag:9eE3TzPHKuucLklaReXydw==,type:str]
    password: ENC[AES256_GCM,data:JLsrI+d0uo4V9AWtghhn7OLCWeDTvrHCDwoH59eh4yI=,iv:Uml5bTRfGJf2wvidDhu5B8iqwME/TO2z5oSqJviD/ag=,tag:93vcyrVRdCWFmuV8qbpZZA==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueklKeFNKOWhwQ3d2dDN3
            ZU9uSnRORTJtS2lIbnVqTHU2c3hla0J4QkNRCkQvbW8rMXd3cStBS0grZWU0ZGdI
            MklTL0RNWCsybXhnOTZXaXlMM0dITnMKLS0tIGg0Sno3RWVseXhZWmo1T29oUElZ
            ZThrL2NYaGwxaVhFcVpOQllHV3Q5SzgK/MDwRyTeUSFA/wZSu9tW9pRxFCV9RxFS
            JjyxQC3ed15ncWE6t/7Iag6qJw6JpflhSS2VZhju5tbgQvWybHmNLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYzJNdlhtb21Zemsya2s1
            LzgvbjNFektxOU5xS2w2WWtPOFdnQjhDMERrCktYUXVTWFphWGpKS2RLcGIyMVlp
            TVVBdUVkVXcyRTQ1NnhQRXVjYVlWWUUKLS0tIGMvZTg1WHd6dmZTNTBISlR5SFZH
            QjAvdlMyQWdQQUozSUJ3MGhoUU9tQ0UK4hK6RYa5YiHL48d0X6Iiz6lk1gb2lD3y
            oLvsKyB4PoUDgkc1QG1l5eNVYqzSNMUJSJKJjA3aUKWL85iQ3+mgNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VWZEM1dRMEpOYklqYlM4
            bDl5dVJUaGhwYXIvWnpuK2F0RkpsNXc3WjE4CjZETFlhQWQyc25SVTY2alorbkc3
            LzRnRzRnSEVTSENHak5ESWI5aDVjS0EKLS0tIGtDcXRRUHhyU3BlSVhWQkF6c0FM
            YmE0bno4bExXc2ZyYVpRc05qQndrTFUKRzqPuTLrxc0enxdo9HG4KQz5X2OB1A1d
            Gw02Jlph1zp19X56iFuob4GAxCcJLR0cWjWwiLNmaMoX2zDCXZDgNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T18:38:17Z"
    mac: ENC[AES256_GCM,data:22rJGQv5AuxBTDzfOpjr0/BILRyGvZ9AwMITF/P2OPuMKZMtBjKltXKvrcyJ9i2dTz4WnXOql6ow/hBY1+5v9lkZNlM9QfE8RPYYtuJ1SAm9TwC3qbHmi6kxPa4bQ6F1e8rBrOibqOa8G3oUwEcHMLT/KWOwzIfXiLUNIvIvH1M=,iv:iJOmXeIn11z8HOZIoQoF1cLq3XXGJWqzimjUoE1eUDQ=,tag:z4NvqWFGhy6PtZvt4UfPQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgres-password
stringData:
    username: ENC[AES256_GCM,data:IN76kzdE5jWV,iv:Eu4Y3ovcJrjZnjThoVOzmj1pjl2CVI98jOV2oBkds4U=,tag:WsXIQz+bj0wy841a/bItJA==,type:str]
    database: ENC[AES256_GCM,data:7AuqmezgD2x/,iv:0mb6QQYi6hmPysSC18fC8Ez8BV0+M26cCj2ep8NqjCI=,tag:pRMaePAFMjXXy74G2Pv6AQ==,type:str]
    port: ENC[AES256_GCM,data:43tsNQ==,iv:Rs4kN0gJBYEZ9RPDvtFnb23TMRGTNb07VHGvN5IQfEg=,tag:oVBdNLZtNOVjM2Z2Y/rOjQ==,type:str]
    hostname: ENC[AES256_GCM,data:oKEbX3j6A6goC2kGyYjssX4GtAS4D/RR7c8ymaaOCUYVrHGYsPc=,iv:HvyX9P+oPgFty+xFTUxtXOx8cpVzrmmCTc8lxsMGKCo=,tag:9eE3TzPHKuucLklaReXydw==,type:str]
    password: ENC[AES256_GCM,data:riUn2vxqDO7jJ+TTRtS8ORc2bc/cUekiI3z2XU5aBg8=,iv:lhEjmRpA6UMZyw0xKihvH5tAWTpETh3/RcVDzB1cD0Q=,tag:+bGEh84SrJo4QhjzvNAb8A==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueklKeFNKOWhwQ3d2dDN3
            ZU9uSnRORTJtS2lIbnVqTHU2c3hla0J4QkNRCkQvbW8rMXd3cStBS0grZWU0ZGdI
            MklTL0RNWCsybXhnOTZXaXlMM0dITnMKLS0tIGg0Sno3RWVseXhZWmo1T29oUElZ
            ZThrL2NYaGwxaVhFcVpOQllHV3Q5SzgK/MDwRyTeUSFA/wZSu9tW9pRxFCV9RxFS
            JjyxQC3ed15ncWE6t/7Iag6qJw6JpflhSS2VZhju5tbgQvWybHmNLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYzJNdlhtb21Zemsya2s1
            LzgvbjNFektxOU5xS2w2WWtPOFdnQjhDMERrCktYUXVTWFphWGpKS2RLcGIyMVlp
            TVVBdUVkVXcyRTQ1NnhQRXVjYVlWWUUKLS0tIGMvZTg1WHd6dmZTNTBISlR5SFZH
            QjAvdlMyQWdQQUozSUJ3MGhoUU9tQ0UK4hK6RYa5YiHL48d0X6Iiz6lk1gb2lD3y
            oLvsKyB4PoUDgkc1QG1l5eNVYqzSNMUJSJKJjA3aUKWL85iQ3+mgNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VWZEM1dRMEpOYklqYlM4
            bDl5dVJUaGhwYXIvWnpuK2F0RkpsNXc3WjE4CjZETFlhQWQyc25SVTY2alorbkc3
            LzRnRzRnSEVTSENHak5ESWI5aDVjS0EKLS0tIGtDcXRRUHhyU3BlSVhWQkF6c0FM
            YmE0bno4bExXc2ZyYVpRc05qQndrTFUKRzqPuTLrxc0enxdo9HG4KQz5X2OB1A1d
            Gw02Jlph1zp19X56iFuob4GAxCcJLR0cWjWwiLNmaMoX2zDCXZDgNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T18:38:17Z"
    mac: ENC[AES256_GCM,data:22rJGQv5AuxBTDzfOpjr0/BILRyGvZ9AwMITF/P2OPuMKZMtBjKltXKvrcyJ9i2dTz4WnXOql6ow/hBY1+5v9lkZNlM9QfE8RPYYtuJ1SAm9TwC3qbHmi6kxPa4bQ6F1e8rBrOibqOa8G3oUwEcHMLT/KWOwzIfXiLUNIvIvH1M=,iv:iJOmXeIn11z8HOZIoQoF1cLq3XXGJWqzimjUoE1eUDQ=,tag:z4NvqWFGhy6PtZvt4UfPQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: oxycloud-postgres-password
stringData:
    username: ENC[AES256_GCM,data:wV/2KkppGaA=,iv:Mmb1Lv/yAoN/M8zNkSoFNCyJpbemZFgGpksIO4nyz5A=,tag:YKPZlebzZBIeYhPEqGpKsA==,type:str]
    database: ENC[AES256_GCM,data:S75Y+7S1vTM=,iv:Z9bMIQ7ky5MUc7BK80/JowNfFLzMaTosJjDuQU4Se14=,tag:p6Zk8bsgTV6a/fWB87ER3g==,type:str]
    port: ENC[AES256_GCM,data:43tsNQ==,iv:Rs4kN0gJBYEZ9RPDvtFnb23TMRGTNb07VHGvN5IQfEg=,tag:oVBdNLZtNOVjM2Z2Y/rOjQ==,type:str]
    hostname: ENC[AES256_GCM,data:oKEbX3j6A6goC2kGyYjssX4GtAS4D/RR7c8ymaaOCUYVrHGYsPc=,iv:HvyX9P+oPgFty+xFTUxtXOx8cpVzrmmCTc8lxsMGKCo=,tag:9eE3TzPHKuucLklaReXydw==,type:str]
    password: ENC[AES256_GCM,data:hbiAIbNORcKf4O4lzckovkHago28Vu31HzyXQ4PAYbQ=,iv:GyNnte1VdXPK76duaSFB49uqBI/yCDhGJcKQGAWIr9A=,tag:A6k1Lgfd1Bu5GJSSTLL/gQ==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueklKeFNKOWhwQ3d2dDN3
            ZU9uSnRORTJtS2lIbnVqTHU2c3hla0J4QkNRCkQvbW8rMXd3cStBS0grZWU0ZGdI
            MklTL0RNWCsybXhnOTZXaXlMM0dITnMKLS0tIGg0Sno3RWVseXhZWmo1T29oUElZ
            ZThrL2NYaGwxaVhFcVpOQllHV3Q5SzgK/MDwRyTeUSFA/wZSu9tW9pRxFCV9RxFS
            JjyxQC3ed15ncWE6t/7Iag6qJw6JpflhSS2VZhju5tbgQvWybHmNLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYzJNdlhtb21Zemsya2s1
            LzgvbjNFektxOU5xS2w2WWtPOFdnQjhDMERrCktYUXVTWFphWGpKS2RLcGIyMVlp
            TVVBdUVkVXcyRTQ1NnhQRXVjYVlWWUUKLS0tIGMvZTg1WHd6dmZTNTBISlR5SFZH
            QjAvdlMyQWdQQUozSUJ3MGhoUU9tQ0UK4hK6RYa5YiHL48d0X6Iiz6lk1gb2lD3y
            oLvsKyB4PoUDgkc1QG1l5eNVYqzSNMUJSJKJjA3aUKWL85iQ3+mgNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VWZEM1dRMEpOYklqYlM4
            bDl5dVJUaGhwYXIvWnpuK2F0RkpsNXc3WjE4CjZETFlhQWQyc25SVTY2alorbkc3
            LzRnRzRnSEVTSENHak5ESWI5aDVjS0EKLS0tIGtDcXRRUHhyU3BlSVhWQkF6c0FM
            YmE0bno4bExXc2ZyYVpRc05qQndrTFUKRzqPuTLrxc0enxdo9HG4KQz5X2OB1A1d
            Gw02Jlph1zp19X56iFuob4GAxCcJLR0cWjWwiLNmaMoX2zDCXZDgNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T18:38:17Z"
    mac: ENC[AES256_GCM,data:22rJGQv5AuxBTDzfOpjr0/BILRyGvZ9AwMITF/P2OPuMKZMtBjKltXKvrcyJ9i2dTz4WnXOql6ow/hBY1+5v9lkZNlM9QfE8RPYYtuJ1SAm9TwC3qbHmi6kxPa4bQ6F1e8rBrOibqOa8G3oUwEcHMLT/KWOwzIfXiLUNIvIvH1M=,iv:iJOmXeIn11z8HOZIoQoF1cLq3XXGJWqzimjUoE1eUDQ=,tag:z4NvqWFGhy6PtZvt4UfPQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
