---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale-operator
spec:
  chart:
    spec:
      chart: tailscale-operator
      version: 1.92.5
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  maxHistory: 3
  interval: 1h
  timeout: 10m
  install:
    createNamespace: true
    replace: true
    remediation:
      retries: 7
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 7
      strategy: rollback
  rollback:
    force: false
    cleanupOnFail: true
    recreate: true
  uninstall:
    keepHistory: false
  dependsOn:
    - name: onepassword-connect
      namespace: kube-system
    - name: external-secrets
      namespace: kube-system
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth
      targetPath: oauth.clientId
      valuesKey: username
    - kind: Secret
      name: tailscale-oauth
      targetPath: oauth.clientSecret
      valuesKey: credential
  values:
    fullnameOverride: *app
    installCRDs: true
    operatorConfig:
      logging: debug
      defaultTags:
        - "tag:operator"
      image:
        repository: ghcr.io/tailscale/k8s-operator
        tag: v1.92.5@sha256:551e085388ca94cf86fe42eecf9a6250ac59f597b05ef98dfbb205219af7746d
        pullPolicy: IfNotPresent
      hostname: "${CLUSTER_CNAME}-operator"
      defaultProxyClass: default
      podAnnotations:
        reloader.stakater.com/auto: "true"
    proxyConfig:
      image:
        repository: tailscale/tailscale
        tag: v1.92.5@sha256:4a0aaacee6f28e724c1f80c986e5776c9c979d8f7e19274c2cae2d495cc8d625
      defaultTags: "tag:apps"
      podAnnotations:
        reloader.stakater.com/auto: "true"
      firewallMode: auto
    apiServerProxyConfig:
      allowImpersonation: true
      mode: "true" # "true", "false", "noauth"
