---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale-operator
spec:
  chart:
    spec:
      chart: tailscale-operator
      version: 1.94.2
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  maxHistory: 3
  interval: 1h
  timeout: 10m
  install:
    createNamespace: true
    replace: true
    remediation:
      retries: 7
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 7
      strategy: rollback
  rollback:
    force: false
    cleanupOnFail: true
    recreate: true
  uninstall:
    keepHistory: false
  dependsOn:
    - name: onepassword-connect
      namespace: kube-system
    - name: external-secrets
      namespace: kube-system
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth
      targetPath: oauth.clientId
      valuesKey: username
    - kind: Secret
      name: tailscale-oauth
      targetPath: oauth.clientSecret
      valuesKey: credential
  values:
    fullnameOverride: *app
    installCRDs: true
    operatorConfig:
      logging: debug
      defaultTags:
        - "tag:operator"
      image:
        repository: ghcr.io/tailscale/k8s-operator
        tag: v1.94.2@sha256:7956bd50dca9dc804b98720df94d112b54af85449ed0bf8cc7fad0346b225067
        pullPolicy: IfNotPresent
      hostname: "${CLUSTER_CNAME}-operator"
      defaultProxyClass: default
      podAnnotations:
        reloader.stakater.com/auto: "true"
    proxyConfig:
      image:
        repository: tailscale/tailscale
        tag: v1.94.2@sha256:95e528798bebe75f39b10e74e7051cf51188ee615934f232ba7ad06a3390ffa1
      defaultTags: "tag:apps"
      podAnnotations:
        reloader.stakater.com/auto: "true"
      firewallMode: auto
    apiServerProxyConfig:
      allowImpersonation: true
      mode: "true" # "true", "false", "noauth"
