---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: pulumi-operator-postgres
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "database/pulumi-operator-postgres"
    reloader.stakater.com/auto: "true"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
    name: pulumi-operator-github
    annotations:
      reloader.stakater.com/auto: "true"
spec:
    itemPath: "vaults/Eris/items/Eris Github Access Token"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
    name: pulumi-operator-passphrase
    annotations:
      reloader.stakater.com/auto: "true"
spec:
    itemPath: "vaults/Eris/items/Pulumi Passphrase"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
    name: pulumi-operator-connect-token
    annotations:
      reloader.stakater.com/auto: "true"
spec:
    itemPath: "vaults/Eris/items/Eris 1Password Connect Access Token"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
    name: truenas-home-operations
    annotations:
      reloader.stakater.com/auto: "true"
spec:
    itemPath: vaults/Eris/items/minio root user
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
    name: authentik-secret
    annotations:
      reloader.stakater.com/auto: "true"
spec:
    itemPath: vaults/Eris/items/Authentik Token
