---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.2.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale-operator
spec:
  chart:
    spec:
      chart: tailscale-operator
      version: 1.90.8
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  maxHistory: 3
  interval: 1h
  timeout: 10m
  install:
    createNamespace: true
    replace: true
    remediation:
      retries: 7
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 7
      strategy: rollback
  rollback:
    force: false # true
    cleanupOnFail: true
    recreate: true
  uninstall:
    keepHistory: false
  dependsOn:
    - name: onepassword-connect
      namespace: kube-system
    - name: external-secrets
      namespace: kube-system
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth
      targetPath: oauth.clientId
      valuesKey: username
    - kind: Secret
      name: tailscale-oauth
      targetPath: oauth.clientSecret
      valuesKey: credential
  values:
    fullnameOverride: *app
    installCRDs: true
    operatorConfig:
      logging: debug
      defaultTags:
        - "tag:operator"
      image:
        repository: ghcr.io/tailscale/k8s-operator
        tag: v1.90.8@sha256:693e3c5a466010b25e1f8d3cd601355bbcc8064f83df8627f80fefa68ebe3f5f
        pullPolicy: IfNotPresent
      hostname: "${CLUSTER_CNAME}-operator"
      defaultProxyClass: default
      podAnnotations:
        reloader.stakater.com/auto: "true"
    proxyConfig:
      image:
        repository: tailscale/tailscale
        tag: v1.90.8@sha256:4dacf554cf34e84c15fb816aa68fb3428993c3d27feeafb86a9b3eb94248c40f
      defaultTags: "tag:apps"
      podAnnotations:
        reloader.stakater.com/auto: "true"
      firewallMode: auto
    apiServerProxyConfig:
      allowImpersonation: true
      mode: "true" # "true", "false", "noauth"
