apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: zitadel
  namespace: idp
spec:
  componentKinds:
    - group: helm.toolkit.fluxcd.io
      kind: HelmRelease
  descriptor:
    type: identity
    version: v1
    description: Zitadel identity provider
    keywords:
      - identity
      - oidc
      - sso
    links:
      - description: Documentation
        url: https://zitadel.com/docs
