apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-values
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: zitadel-values
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      templateFrom:
      - target: Data
        configMap:
          name: zitadel-values
          items:
          - key: values.yaml
            templateAs: Values
  dataFrom:
    - extract:
        key: 'Zitadel Master Key'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
    - extract:
        key: 'zitadel-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
