---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret-values.yaml
  - ./externalsecret-config.yaml
  - ./masterkey.yaml
  - ./helmrelease.yaml
  - ./definition.yaml
  - ./httproute.yaml
  - ./push-secrets.yaml
configMapGenerator:
  - name: zitadel-values
    files:
      - values.yaml=resources/values.yaml
  - name: zitadel-config
    files:
      - config.yaml=resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
