---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: definition-crds-push-secret
spec:
  deletionPolicy: None
  refreshInterval: 4m
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword-connect
  selector:
    secret:
      name: login-client
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: &key zitadel-login-client
          property: login-client
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
