---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: zitadel-login-client-push-secret
spec:
  deletionPolicy: None
  refreshInterval: 4m
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword-connect
  selector:
    secret:
      name: login-client
  data:
    - match:
        secretKey: pat
        remoteRef:
          remoteKey: zitadel-login-client
          property: pat
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: zitadel-machine-pat-push-secret
spec:
  deletionPolicy: None
  refreshInterval: 4m
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword-connect
  selector:
    secret:
      name: zitadel-machine-pat
  data:
    - match:
        secretKey: pat
        remoteRef:
          remoteKey: zitadel-machine-pat
          property: pat
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: zitadel-machine-push-secret
spec:
  deletionPolicy: None
  refreshInterval: 4m
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword-connect
  selector:
    secret:
      name: zitadel-machine
  data:
    - match:
        secretKey: zitadel-machine.json
        remoteRef:
          remoteKey: zitadel-machine
          property: zitadel-machine.json
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec: {}
