apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-user-push-secret.yaml
  - postgres-superuser-push-secret.yaml
  - authentik-postgres-push-secret.yaml
  - crowdsec-postgres-push-secret.yaml