---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./github-auth.yaml
configMapGenerator:
  - files:
      - github-auth-script.sh=./resources/github-auth-script.sh
    name: github-auth-script
generatorOptions:
  disableNameSuffixHash: true
