---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: home-assistant
spec:
  name: Home Assistant
  category: Applications
  description: Home automation and things that make the house angry.
  url: https://home.${ROOT_DOMAIN}/auth/oidc/welcome
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/home-assistant.svg
  access_policy:
    groups:
      - friends
      - family
  authentik:
    oauth2:
      clientType: confidential
      allowedRedirectUris:
      - url: "https://home.${ROOT_DOMAIN}/auth/oidc/callback"
      - url: "https://home.${TAILSCALE_DOMAIN}/auth/oidc/callback"
      - url: "https://${APP}.${ROOT_DOMAIN}/auth/oidc/callback"
      propertyMappings:
        - email
        - openid
        - profile
      includeClaimsInIdToken: true
      subMode: user_email
  gatus:
    - url: https://home.${ROOT_DOMAIN}
      method: GET
      conditions:
        - "[STATUS] == 200"
