---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ts-egress
spec:
  type: egress
  replicas: 3
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ts-ingress
spec:
  type: ingress
  replicas: 3
